// Code generated by protoc-gen-go. DO NOT EDIT.
// source: douyin-miniapp/credential.proto

package douyin_miniapp // import "github.com/dev-openapi/douyin-miniapp"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetAccessTokenReq struct {
	Appid                string   `protobuf:"bytes,1,opt,name=appid" json:"appid,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
	GrantType            string   `protobuf:"bytes,3,opt,name=grant_type,json=grantType" json:"grant_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenReq) Reset()         { *m = GetAccessTokenReq{} }
func (m *GetAccessTokenReq) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenReq) ProtoMessage()    {}
func (*GetAccessTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_credential_da136f6ff8eea5f2, []int{0}
}
func (m *GetAccessTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenReq.Unmarshal(m, b)
}
func (m *GetAccessTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenReq.Marshal(b, m, deterministic)
}
func (dst *GetAccessTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenReq.Merge(dst, src)
}
func (m *GetAccessTokenReq) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenReq.Size(m)
}
func (m *GetAccessTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenReq proto.InternalMessageInfo

func (m *GetAccessTokenReq) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *GetAccessTokenReq) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *GetAccessTokenReq) GetGrantType() string {
	if m != nil {
		return m.GrantType
	}
	return ""
}

type GetAccessTokenRes struct {
	ErrNo                int64    `protobuf:"varint,1,opt,name=err_no,json=errNo" json:"err_no,omitempty"`
	ErrTips              string   `protobuf:"bytes,2,opt,name=err_tips,json=errTips" json:"err_tips,omitempty"`
	AccessToken          string   `protobuf:"bytes,10,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	ExpiresIn            int64    `protobuf:"varint,11,opt,name=expires_in,json=expiresIn" json:"expires_in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenRes) Reset()         { *m = GetAccessTokenRes{} }
func (m *GetAccessTokenRes) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenRes) ProtoMessage()    {}
func (*GetAccessTokenRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_credential_da136f6ff8eea5f2, []int{1}
}
func (m *GetAccessTokenRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenRes.Unmarshal(m, b)
}
func (m *GetAccessTokenRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenRes.Marshal(b, m, deterministic)
}
func (dst *GetAccessTokenRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenRes.Merge(dst, src)
}
func (m *GetAccessTokenRes) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenRes.Size(m)
}
func (m *GetAccessTokenRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenRes proto.InternalMessageInfo

func (m *GetAccessTokenRes) GetErrNo() int64 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *GetAccessTokenRes) GetErrTips() string {
	if m != nil {
		return m.ErrTips
	}
	return ""
}

func (m *GetAccessTokenRes) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetAccessTokenRes) GetExpiresIn() int64 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func init() {
	proto.RegisterType((*GetAccessTokenReq)(nil), "developer.toutiao.com.GetAccessTokenReq")
	proto.RegisterType((*GetAccessTokenRes)(nil), "developer.toutiao.com.GetAccessTokenRes")
}

func init() {
	proto.RegisterFile("douyin-miniapp/credential.proto", fileDescriptor_credential_da136f6ff8eea5f2)
}

var fileDescriptor_credential_da136f6ff8eea5f2 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0xb1, 0x4a, 0x03, 0x41,
	0x10, 0xe5, 0x12, 0x12, 0xcd, 0x46, 0x84, 0x2c, 0x46, 0xcf, 0x60, 0x50, 0x0f, 0xc4, 0x20, 0xe4,
	0x0e, 0x62, 0x67, 0xa7, 0x16, 0x62, 0x63, 0x11, 0x53, 0xd9, 0x9c, 0x9b, 0xbb, 0xe1, 0x5c, 0x4c,
	0x76, 0xc6, 0xdd, 0xcd, 0x61, 0x5a, 0x2d, 0xfc, 0x00, 0x2b, 0xbf, 0xcb, 0x5f, 0xf0, 0x43, 0xe4,
	0x36, 0x87, 0x12, 0x62, 0x61, 0x39, 0x6f, 0x66, 0xde, 0x9b, 0x79, 0x8f, 0xed, 0xa7, 0x38, 0x9b,
	0x4b, 0xd5, 0x9f, 0x4a, 0x25, 0x05, 0x51, 0x94, 0x68, 0x48, 0x41, 0x59, 0x29, 0x26, 0x21, 0x69,
	0xb4, 0xc8, 0xdb, 0x29, 0xe4, 0x30, 0x41, 0x02, 0x1d, 0x5a, 0x9c, 0x59, 0x29, 0x30, 0x4c, 0x70,
	0xda, 0xd9, 0xcb, 0x10, 0xb3, 0x09, 0x44, 0x82, 0x64, 0x24, 0x94, 0x42, 0x2b, 0xac, 0x44, 0x65,
	0x16, 0x4b, 0xc1, 0x3d, 0x6b, 0x5d, 0x81, 0x3d, 0x4f, 0x12, 0x30, 0x66, 0x84, 0x8f, 0xa0, 0x86,
	0xf0, 0xc4, 0xb7, 0x58, 0x4d, 0x10, 0xc9, 0xd4, 0xf7, 0x0e, 0xbc, 0x5e, 0x63, 0xb8, 0x28, 0xf8,
	0x36, 0xab, 0x1b, 0x48, 0x34, 0x58, 0xbf, 0xe2, 0xe0, 0xb2, 0xe2, 0x5d, 0xc6, 0x32, 0x2d, 0x94,
	0x8d, 0xed, 0x9c, 0xc0, 0xaf, 0xba, 0x5e, 0xc3, 0x21, 0xa3, 0x39, 0x41, 0xf0, 0xe6, 0xad, 0x4a,
	0x18, 0xde, 0x66, 0x75, 0xd0, 0x3a, 0x56, 0xe8, 0x34, 0xaa, 0xc3, 0x1a, 0x68, 0x7d, 0x83, 0x7c,
	0x97, 0xad, 0x17, 0xb0, 0x95, 0x64, 0x4a, 0x95, 0x35, 0xd0, 0x7a, 0x24, 0xc9, 0xf0, 0x43, 0xb6,
	0x21, 0x1c, 0x47, 0x6c, 0x0b, 0x12, 0x9f, 0xb9, 0x76, 0x53, 0xfc, 0xf2, 0x16, 0x97, 0xc0, 0x33,
	0x49, 0x0d, 0x26, 0x96, 0xca, 0x6f, 0x3a, 0xe2, 0x46, 0x89, 0x5c, 0xab, 0xc1, 0x87, 0xc7, 0x5a,
	0x97, 0x3f, 0xae, 0xdd, 0x82, 0xce, 0x65, 0x02, 0xfc, 0xd5, 0x63, 0x9b, 0xcb, 0xf7, 0xf1, 0x5e,
	0xf8, 0xa7, 0x95, 0xe1, 0x8a, 0x53, 0x9d, 0xff, 0x4e, 0x9a, 0xa0, 0xfb, 0xf2, 0xf9, 0xf5, 0x5e,
	0xd9, 0x09, 0xf8, 0x22, 0x08, 0x22, 0x13, 0xe5, 0x83, 0xc8, 0xbd, 0x72, 0xe6, 0x9d, 0x5c, 0x1c,
	0xdf, 0x1d, 0x65, 0xd2, 0x3e, 0xcc, 0xc6, 0xc5, 0x7a, 0x94, 0x42, 0xde, 0x47, 0x02, 0x55, 0x8c,
	0x2e, 0xc7, 0x3e, 0xae, 0xbb, 0xdc, 0x4e, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xe4, 0x0d,
	0x81, 0x0f, 0x02, 0x00, 0x00,
}
