// 抖音小程序开放接口-接口调用凭证 douyin-miniapp

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.0
// source: douyin-miniapp/credential.proto

package douyin_miniapp

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccessTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appid     string `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"`                          // 小程序 ID
	Secret    string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`                        // 小程序的 APP Secret，可以在开发者后台获取
	GrantType string `protobuf:"bytes,3,opt,name=grant_type,json=grantType,proto3" json:"grant_type,omitempty"` // 获取 access_token 时值为 client_credential
}

func (x *GetAccessTokenReq) Reset() {
	*x = GetAccessTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_douyin_miniapp_credential_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccessTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessTokenReq) ProtoMessage() {}

func (x *GetAccessTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_douyin_miniapp_credential_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessTokenReq.ProtoReflect.Descriptor instead.
func (*GetAccessTokenReq) Descriptor() ([]byte, []int) {
	return file_douyin_miniapp_credential_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccessTokenReq) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

func (x *GetAccessTokenReq) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *GetAccessTokenReq) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

type GetAccessTokenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrNo       int64  `protobuf:"varint,1,opt,name=err_no,json=errNo,proto3" json:"err_no,omitempty"`                   // 错误码
	ErrTips     string `protobuf:"bytes,2,opt,name=err_tips,json=errTips,proto3" json:"err_tips,omitempty"`              // 错误信息
	AccessToken string `protobuf:"bytes,10,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // 获取的 access_token
	ExpiresIn   int64  `protobuf:"varint,11,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`      // access_token 有效时间，单位：秒
}

func (x *GetAccessTokenRes) Reset() {
	*x = GetAccessTokenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_douyin_miniapp_credential_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccessTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessTokenRes) ProtoMessage() {}

func (x *GetAccessTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_douyin_miniapp_credential_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessTokenRes.ProtoReflect.Descriptor instead.
func (*GetAccessTokenRes) Descriptor() ([]byte, []int) {
	return file_douyin_miniapp_credential_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccessTokenRes) GetErrNo() int64 {
	if x != nil {
		return x.ErrNo
	}
	return 0
}

func (x *GetAccessTokenRes) GetErrTips() string {
	if x != nil {
		return x.ErrTips
	}
	return ""
}

func (x *GetAccessTokenRes) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetAccessTokenRes) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

var File_douyin_miniapp_credential_proto protoreflect.FileDescriptor

var file_douyin_miniapp_credential_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2d, 0x6d, 0x69, 0x6e, 0x69, 0x61, 0x70, 0x70,
	0x2f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x15, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x74, 0x6f, 0x75,
	0x74, 0x69, 0x61, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x70, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x61,
	0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67,
	0x72, 0x61, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x87, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x15,
	0x0a, 0x06, 0x65, 0x72, 0x72, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x4e, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x74, 0x69, 0x70,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x54, 0x69, 0x70, 0x73,
	0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x69,
	0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73,
	0x49, 0x6e, 0x32, 0x99, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x83, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x28, 0x2e, 0x64, 0x65,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x74, 0x6f, 0x75, 0x74, 0x69, 0x61, 0x6f, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x28, 0x2e, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65,
	0x72, 0x2e, 0x74, 0x6f, 0x75, 0x74, 0x69, 0x61, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x22,
	0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x22, 0x12, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70,
	0x70, 0x73, 0x2f, 0x76, 0x32, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x3a, 0x01, 0x2a, 0x42, 0x27,
	0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x76,
	0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2d,
	0x6d, 0x69, 0x6e, 0x69, 0x61, 0x70, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_douyin_miniapp_credential_proto_rawDescOnce sync.Once
	file_douyin_miniapp_credential_proto_rawDescData = file_douyin_miniapp_credential_proto_rawDesc
)

func file_douyin_miniapp_credential_proto_rawDescGZIP() []byte {
	file_douyin_miniapp_credential_proto_rawDescOnce.Do(func() {
		file_douyin_miniapp_credential_proto_rawDescData = protoimpl.X.CompressGZIP(file_douyin_miniapp_credential_proto_rawDescData)
	})
	return file_douyin_miniapp_credential_proto_rawDescData
}

var file_douyin_miniapp_credential_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_douyin_miniapp_credential_proto_goTypes = []interface{}{
	(*GetAccessTokenReq)(nil), // 0: developer.toutiao.com.GetAccessTokenReq
	(*GetAccessTokenRes)(nil), // 1: developer.toutiao.com.GetAccessTokenRes
}
var file_douyin_miniapp_credential_proto_depIdxs = []int32{
	0, // 0: developer.toutiao.com.CredentialService.GetAccessToken:input_type -> developer.toutiao.com.GetAccessTokenReq
	1, // 1: developer.toutiao.com.CredentialService.GetAccessToken:output_type -> developer.toutiao.com.GetAccessTokenRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_douyin_miniapp_credential_proto_init() }
func file_douyin_miniapp_credential_proto_init() {
	if File_douyin_miniapp_credential_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_douyin_miniapp_credential_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccessTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_douyin_miniapp_credential_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccessTokenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_douyin_miniapp_credential_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_douyin_miniapp_credential_proto_goTypes,
		DependencyIndexes: file_douyin_miniapp_credential_proto_depIdxs,
		MessageInfos:      file_douyin_miniapp_credential_proto_msgTypes,
	}.Build()
	File_douyin_miniapp_credential_proto = out.File
	file_douyin_miniapp_credential_proto_rawDesc = nil
	file_douyin_miniapp_credential_proto_goTypes = nil
	file_douyin_miniapp_credential_proto_depIdxs = nil
}
