// 抖音小程序开放接口-客服开放接口
// douyin-miniapp

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.0
// source: douyin-miniapp/customer.proto

package douyin_miniapp

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCustomerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appid   string `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Openid  string `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Scene   string `protobuf:"bytes,4,opt,name=scene,proto3" json:"scene,omitempty"`
	OrderId string `protobuf:"bytes,5,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ImType  string `protobuf:"bytes,6,opt,name=im_type,json=imType,proto3" json:"im_type,omitempty"`
}

func (x *GetCustomerReq) Reset() {
	*x = GetCustomerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_douyin_miniapp_customer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCustomerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerReq) ProtoMessage() {}

func (x *GetCustomerReq) ProtoReflect() protoreflect.Message {
	mi := &file_douyin_miniapp_customer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerReq.ProtoReflect.Descriptor instead.
func (*GetCustomerReq) Descriptor() ([]byte, []int) {
	return file_douyin_miniapp_customer_proto_rawDescGZIP(), []int{0}
}

func (x *GetCustomerReq) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

func (x *GetCustomerReq) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *GetCustomerReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetCustomerReq) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *GetCustomerReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetCustomerReq) GetImType() string {
	if x != nil {
		return x.ImType
	}
	return ""
}

type GetCustomerData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetCustomerData) Reset() {
	*x = GetCustomerData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_douyin_miniapp_customer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCustomerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerData) ProtoMessage() {}

func (x *GetCustomerData) ProtoReflect() protoreflect.Message {
	mi := &file_douyin_miniapp_customer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerData.ProtoReflect.Descriptor instead.
func (*GetCustomerData) Descriptor() ([]byte, []int) {
	return file_douyin_miniapp_customer_proto_rawDescGZIP(), []int{1}
}

func (x *GetCustomerData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetCustomerRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrNo  int32            `protobuf:"varint,2,opt,name=err_no,json=errNo,proto3" json:"err_no,omitempty"`
	ErrMsg string           `protobuf:"bytes,3,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	LogId  string           `protobuf:"bytes,4,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Data   *GetCustomerData `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetCustomerRes) Reset() {
	*x = GetCustomerRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_douyin_miniapp_customer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCustomerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerRes) ProtoMessage() {}

func (x *GetCustomerRes) ProtoReflect() protoreflect.Message {
	mi := &file_douyin_miniapp_customer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerRes.ProtoReflect.Descriptor instead.
func (*GetCustomerRes) Descriptor() ([]byte, []int) {
	return file_douyin_miniapp_customer_proto_rawDescGZIP(), []int{2}
}

func (x *GetCustomerRes) GetErrNo() int32 {
	if x != nil {
		return x.ErrNo
	}
	return 0
}

func (x *GetCustomerRes) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *GetCustomerRes) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *GetCustomerRes) GetData() *GetCustomerData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_douyin_miniapp_customer_proto protoreflect.FileDescriptor

var file_douyin_miniapp_customer_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2d, 0x6d, 0x69, 0x6e, 0x69, 0x61, 0x70, 0x70,
	0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x15, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x74, 0x6f, 0x75, 0x74, 0x69,
	0x61, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9c, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f,
	0x70, 0x65, 0x6e, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x6d,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x23, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x93, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x65,
	0x72, 0x72, 0x5f, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x4e, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x6c,
	0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67,
	0x49, 0x64, 0x12, 0x3a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x74, 0x6f, 0x75,
	0x74, 0x69, 0x61, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x9c,
	0x01, 0x0a, 0x0f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x88, 0x01, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x12, 0x25, 0x2e, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x74,
	0x6f, 0x75, 0x74, 0x69, 0x61, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x64, 0x65, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x74, 0x6f, 0x75, 0x74, 0x69, 0x61, 0x6f, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x22, 0x2b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x25, 0x12, 0x23, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x70, 0x70, 0x73, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x42, 0x27, 0x5a,
	0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x76, 0x2d,
	0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2d, 0x6d,
	0x69, 0x6e, 0x69, 0x61, 0x70, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_douyin_miniapp_customer_proto_rawDescOnce sync.Once
	file_douyin_miniapp_customer_proto_rawDescData = file_douyin_miniapp_customer_proto_rawDesc
)

func file_douyin_miniapp_customer_proto_rawDescGZIP() []byte {
	file_douyin_miniapp_customer_proto_rawDescOnce.Do(func() {
		file_douyin_miniapp_customer_proto_rawDescData = protoimpl.X.CompressGZIP(file_douyin_miniapp_customer_proto_rawDescData)
	})
	return file_douyin_miniapp_customer_proto_rawDescData
}

var file_douyin_miniapp_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_douyin_miniapp_customer_proto_goTypes = []interface{}{
	(*GetCustomerReq)(nil),  // 0: developer.toutiao.com.GetCustomerReq
	(*GetCustomerData)(nil), // 1: developer.toutiao.com.GetCustomerData
	(*GetCustomerRes)(nil),  // 2: developer.toutiao.com.GetCustomerRes
}
var file_douyin_miniapp_customer_proto_depIdxs = []int32{
	1, // 0: developer.toutiao.com.GetCustomerRes.data:type_name -> developer.toutiao.com.GetCustomerData
	0, // 1: developer.toutiao.com.CustomerService.GetCustomer:input_type -> developer.toutiao.com.GetCustomerReq
	2, // 2: developer.toutiao.com.CustomerService.GetCustomer:output_type -> developer.toutiao.com.GetCustomerRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_douyin_miniapp_customer_proto_init() }
func file_douyin_miniapp_customer_proto_init() {
	if File_douyin_miniapp_customer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_douyin_miniapp_customer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCustomerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_douyin_miniapp_customer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCustomerData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_douyin_miniapp_customer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCustomerRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_douyin_miniapp_customer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_douyin_miniapp_customer_proto_goTypes,
		DependencyIndexes: file_douyin_miniapp_customer_proto_depIdxs,
		MessageInfos:      file_douyin_miniapp_customer_proto_msgTypes,
	}.Build()
	File_douyin_miniapp_customer_proto = out.File
	file_douyin_miniapp_customer_proto_rawDesc = nil
	file_douyin_miniapp_customer_proto_goTypes = nil
	file_douyin_miniapp_customer_proto_depIdxs = nil
}
