// Code generated by protoc-gen-go. DO NOT EDIT.
// source: douyin-miniapp/customer.proto

package douyin_miniapp // import "github.com/dev-openapi/douyin-miniapp"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetCustomerReq struct {
	Appid                string   `protobuf:"bytes,1,opt,name=appid" json:"appid,omitempty"`
	Openid               string   `protobuf:"bytes,2,opt,name=openid" json:"openid,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Scene                string   `protobuf:"bytes,4,opt,name=scene" json:"scene,omitempty"`
	OrderId              string   `protobuf:"bytes,5,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	ImType               string   `protobuf:"bytes,6,opt,name=im_type,json=imType" json:"im_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomerReq) Reset()         { *m = GetCustomerReq{} }
func (m *GetCustomerReq) String() string { return proto.CompactTextString(m) }
func (*GetCustomerReq) ProtoMessage()    {}
func (*GetCustomerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_d83740232bc0fe30, []int{0}
}
func (m *GetCustomerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerReq.Unmarshal(m, b)
}
func (m *GetCustomerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerReq.Marshal(b, m, deterministic)
}
func (dst *GetCustomerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerReq.Merge(dst, src)
}
func (m *GetCustomerReq) XXX_Size() int {
	return xxx_messageInfo_GetCustomerReq.Size(m)
}
func (m *GetCustomerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerReq proto.InternalMessageInfo

func (m *GetCustomerReq) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *GetCustomerReq) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

func (m *GetCustomerReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetCustomerReq) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *GetCustomerReq) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *GetCustomerReq) GetImType() string {
	if m != nil {
		return m.ImType
	}
	return ""
}

type GetCustomerData struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomerData) Reset()         { *m = GetCustomerData{} }
func (m *GetCustomerData) String() string { return proto.CompactTextString(m) }
func (*GetCustomerData) ProtoMessage()    {}
func (*GetCustomerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_d83740232bc0fe30, []int{1}
}
func (m *GetCustomerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerData.Unmarshal(m, b)
}
func (m *GetCustomerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerData.Marshal(b, m, deterministic)
}
func (dst *GetCustomerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerData.Merge(dst, src)
}
func (m *GetCustomerData) XXX_Size() int {
	return xxx_messageInfo_GetCustomerData.Size(m)
}
func (m *GetCustomerData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerData.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerData proto.InternalMessageInfo

func (m *GetCustomerData) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type GetCustomerRes struct {
	ErrNo                int32            `protobuf:"varint,2,opt,name=err_no,json=errNo" json:"err_no,omitempty"`
	ErrMsg               string           `protobuf:"bytes,3,opt,name=err_msg,json=errMsg" json:"err_msg,omitempty"`
	LogId                string           `protobuf:"bytes,4,opt,name=log_id,json=logId" json:"log_id,omitempty"`
	Data                 *GetCustomerData `protobuf:"bytes,10,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetCustomerRes) Reset()         { *m = GetCustomerRes{} }
func (m *GetCustomerRes) String() string { return proto.CompactTextString(m) }
func (*GetCustomerRes) ProtoMessage()    {}
func (*GetCustomerRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_d83740232bc0fe30, []int{2}
}
func (m *GetCustomerRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerRes.Unmarshal(m, b)
}
func (m *GetCustomerRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerRes.Marshal(b, m, deterministic)
}
func (dst *GetCustomerRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerRes.Merge(dst, src)
}
func (m *GetCustomerRes) XXX_Size() int {
	return xxx_messageInfo_GetCustomerRes.Size(m)
}
func (m *GetCustomerRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerRes proto.InternalMessageInfo

func (m *GetCustomerRes) GetErrNo() int32 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *GetCustomerRes) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *GetCustomerRes) GetLogId() string {
	if m != nil {
		return m.LogId
	}
	return ""
}

func (m *GetCustomerRes) GetData() *GetCustomerData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*GetCustomerReq)(nil), "developer.toutiao.com.GetCustomerReq")
	proto.RegisterType((*GetCustomerData)(nil), "developer.toutiao.com.GetCustomerData")
	proto.RegisterType((*GetCustomerRes)(nil), "developer.toutiao.com.GetCustomerRes")
}

func init() {
	proto.RegisterFile("douyin-miniapp/customer.proto", fileDescriptor_customer_d83740232bc0fe30)
}

var fileDescriptor_customer_d83740232bc0fe30 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0xca, 0xd3, 0x40,
	0x14, 0x85, 0xc9, 0xff, 0x37, 0xa9, 0x4e, 0xc1, 0xca, 0x60, 0x35, 0x16, 0x85, 0x92, 0x52, 0x2d,
	0x48, 0x13, 0xa8, 0x3b, 0x97, 0x2a, 0x48, 0x17, 0xba, 0x88, 0xae, 0xdc, 0x84, 0x69, 0xe6, 0x92,
	0x0e, 0x24, 0x73, 0xa7, 0x33, 0x93, 0x42, 0xb7, 0xae, 0xdc, 0x77, 0xdb, 0xb7, 0xf2, 0x15, 0x7c,
	0x10, 0x99, 0x49, 0x94, 0x5a, 0x04, 0xff, 0xdd, 0x9c, 0x93, 0x73, 0x4f, 0xbe, 0x64, 0x2e, 0x79,
	0xce, 0xb1, 0x3d, 0x0a, 0xb9, 0x6a, 0x84, 0x14, 0x4c, 0xa9, 0xac, 0x6c, 0x8d, 0xc5, 0x06, 0x74,
	0xaa, 0x34, 0x5a, 0xa4, 0x13, 0x0e, 0x07, 0xa8, 0x51, 0x81, 0x4e, 0x2d, 0xb6, 0x56, 0x30, 0x4c,
	0x4b, 0x6c, 0xa6, 0xcf, 0x2a, 0xc4, 0xaa, 0x86, 0x8c, 0x29, 0x91, 0x31, 0x29, 0xd1, 0x32, 0x2b,
	0x50, 0x9a, 0x6e, 0x28, 0x39, 0x07, 0xe4, 0xc1, 0x07, 0xb0, 0xef, 0xfa, 0xaa, 0x1c, 0xf6, 0xf4,
	0x11, 0x09, 0x99, 0x52, 0x82, 0xc7, 0xc1, 0x2c, 0x58, 0xde, 0xcf, 0x3b, 0x41, 0x1f, 0x93, 0x08,
	0x15, 0x48, 0xc1, 0xe3, 0x1b, 0x6f, 0xf7, 0x8a, 0x52, 0x32, 0xb0, 0x47, 0x05, 0xf1, 0xad, 0x77,
	0xfd, 0xd9, 0x35, 0x98, 0x12, 0x24, 0xc4, 0x83, 0xae, 0xc1, 0x0b, 0xfa, 0x94, 0xdc, 0x43, 0xcd,
	0x41, 0x17, 0x82, 0xc7, 0xa1, 0x7f, 0x30, 0xf4, 0x7a, 0xc3, 0xe9, 0x13, 0x32, 0x14, 0x4d, 0xe1,
	0x7b, 0xa2, 0xae, 0x5d, 0x34, 0x5f, 0x8e, 0x0a, 0x92, 0x39, 0x19, 0x5f, 0xd0, 0xbd, 0x67, 0x96,
	0xd1, 0x87, 0xe4, 0xb6, 0xd5, 0x75, 0x0f, 0xe7, 0x8e, 0xc9, 0xe9, 0xfa, 0x1b, 0x0c, 0x9d, 0x90,
	0x08, 0xb4, 0x2e, 0x24, 0x7a, 0xda, 0x30, 0x0f, 0x41, 0xeb, 0x4f, 0xe8, 0xde, 0xe3, 0xec, 0xc6,
	0x54, 0x3d, 0xaf, 0x4b, 0x7d, 0x34, 0x95, 0xcb, 0xd7, 0x58, 0x39, 0xb2, 0x1e, 0xb9, 0xc6, 0x6a,
	0xc3, 0xe9, 0x1b, 0x32, 0xe0, 0xcc, 0xb2, 0x98, 0xcc, 0x82, 0xe5, 0x68, 0xfd, 0x22, 0xfd, 0xe7,
	0x1f, 0x4e, 0xaf, 0x08, 0x73, 0x3f, 0xb3, 0x3e, 0x07, 0x64, 0xfc, 0xdb, 0xfe, 0x0c, 0xfa, 0x20,
	0x4a, 0xa0, 0xdf, 0x03, 0x32, 0xba, 0x48, 0xd3, 0xc5, 0xff, 0x1b, 0x73, 0xd8, 0x4f, 0xef, 0x14,
	0x33, 0xc9, 0xab, 0x6f, 0x3f, 0x7e, 0x9e, 0x6e, 0x16, 0x74, 0xde, 0xdd, 0xb5, 0x52, 0x26, 0x2b,
	0x77, 0xcc, 0xfe, 0xd9, 0x93, 0xc2, 0x74, 0x18, 0x45, 0xab, 0xeb, 0xb7, 0x2f, 0xbf, 0x2e, 0x2a,
	0x61, 0x77, 0xed, 0xd6, 0x35, 0x65, 0x1c, 0x0e, 0x2b, 0x77, 0xa1, 0x6e, 0xf0, 0xef, 0x2d, 0xdb,
	0x46, 0x7e, 0x51, 0x5e, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x52, 0xe7, 0x0b, 0x7e, 0x02,
	0x00, 0x00,
}
