// Code generated by protoc-gen-go. DO NOT EDIT.
// source: douyin-miniapp/datacache.proto

package douyin_miniapp // import "github.com/dev-openapi/douyin-miniapp"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KvItem struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KvItem) Reset()         { *m = KvItem{} }
func (m *KvItem) String() string { return proto.CompactTextString(m) }
func (*KvItem) ProtoMessage()    {}
func (*KvItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_datacache_65802314915f62bf, []int{0}
}
func (m *KvItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KvItem.Unmarshal(m, b)
}
func (m *KvItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KvItem.Marshal(b, m, deterministic)
}
func (dst *KvItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KvItem.Merge(dst, src)
}
func (m *KvItem) XXX_Size() int {
	return xxx_messageInfo_KvItem.Size(m)
}
func (m *KvItem) XXX_DiscardUnknown() {
	xxx_messageInfo_KvItem.DiscardUnknown(m)
}

var xxx_messageInfo_KvItem proto.InternalMessageInfo

func (m *KvItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KvItem) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SetUserStorageReq struct {
	AccessToken          string                  `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	Openid               string                  `protobuf:"bytes,2,opt,name=openid" json:"openid,omitempty"`
	Signature            string                  `protobuf:"bytes,3,opt,name=signature" json:"signature,omitempty"`
	SigMethod            string                  `protobuf:"bytes,4,opt,name=sig_method,json=sigMethod" json:"sig_method,omitempty"`
	Body                 *SetUserStorageReq_Body `protobuf:"bytes,10,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SetUserStorageReq) Reset()         { *m = SetUserStorageReq{} }
func (m *SetUserStorageReq) String() string { return proto.CompactTextString(m) }
func (*SetUserStorageReq) ProtoMessage()    {}
func (*SetUserStorageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_datacache_65802314915f62bf, []int{1}
}
func (m *SetUserStorageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserStorageReq.Unmarshal(m, b)
}
func (m *SetUserStorageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserStorageReq.Marshal(b, m, deterministic)
}
func (dst *SetUserStorageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserStorageReq.Merge(dst, src)
}
func (m *SetUserStorageReq) XXX_Size() int {
	return xxx_messageInfo_SetUserStorageReq.Size(m)
}
func (m *SetUserStorageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserStorageReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserStorageReq proto.InternalMessageInfo

func (m *SetUserStorageReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *SetUserStorageReq) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

func (m *SetUserStorageReq) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *SetUserStorageReq) GetSigMethod() string {
	if m != nil {
		return m.SigMethod
	}
	return ""
}

func (m *SetUserStorageReq) GetBody() *SetUserStorageReq_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type SetUserStorageReq_Body struct {
	KvList               []*KvItem `protobuf:"bytes,1,rep,name=kv_list,json=kvList" json:"kv_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SetUserStorageReq_Body) Reset()         { *m = SetUserStorageReq_Body{} }
func (m *SetUserStorageReq_Body) String() string { return proto.CompactTextString(m) }
func (*SetUserStorageReq_Body) ProtoMessage()    {}
func (*SetUserStorageReq_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_datacache_65802314915f62bf, []int{1, 0}
}
func (m *SetUserStorageReq_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserStorageReq_Body.Unmarshal(m, b)
}
func (m *SetUserStorageReq_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserStorageReq_Body.Marshal(b, m, deterministic)
}
func (dst *SetUserStorageReq_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserStorageReq_Body.Merge(dst, src)
}
func (m *SetUserStorageReq_Body) XXX_Size() int {
	return xxx_messageInfo_SetUserStorageReq_Body.Size(m)
}
func (m *SetUserStorageReq_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserStorageReq_Body.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserStorageReq_Body proto.InternalMessageInfo

func (m *SetUserStorageReq_Body) GetKvList() []*KvItem {
	if m != nil {
		return m.KvList
	}
	return nil
}

type SetUserStorageRes struct {
	Error                int64    `protobuf:"varint,1,opt,name=error" json:"error,omitempty"`
	Errcode              int64    `protobuf:"varint,2,opt,name=errcode" json:"errcode,omitempty"`
	Errmsg               string   `protobuf:"bytes,3,opt,name=errmsg" json:"errmsg,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserStorageRes) Reset()         { *m = SetUserStorageRes{} }
func (m *SetUserStorageRes) String() string { return proto.CompactTextString(m) }
func (*SetUserStorageRes) ProtoMessage()    {}
func (*SetUserStorageRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_datacache_65802314915f62bf, []int{2}
}
func (m *SetUserStorageRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserStorageRes.Unmarshal(m, b)
}
func (m *SetUserStorageRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserStorageRes.Marshal(b, m, deterministic)
}
func (dst *SetUserStorageRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserStorageRes.Merge(dst, src)
}
func (m *SetUserStorageRes) XXX_Size() int {
	return xxx_messageInfo_SetUserStorageRes.Size(m)
}
func (m *SetUserStorageRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserStorageRes.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserStorageRes proto.InternalMessageInfo

func (m *SetUserStorageRes) GetError() int64 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *SetUserStorageRes) GetErrcode() int64 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *SetUserStorageRes) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *SetUserStorageRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RemoveUserStorageReq struct {
	AccessToken          string                     `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	Openid               string                     `protobuf:"bytes,2,opt,name=openid" json:"openid,omitempty"`
	Signature            string                     `protobuf:"bytes,3,opt,name=signature" json:"signature,omitempty"`
	SigMethod            string                     `protobuf:"bytes,4,opt,name=sig_method,json=sigMethod" json:"sig_method,omitempty"`
	Body                 *RemoveUserStorageReq_Body `protobuf:"bytes,10,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RemoveUserStorageReq) Reset()         { *m = RemoveUserStorageReq{} }
func (m *RemoveUserStorageReq) String() string { return proto.CompactTextString(m) }
func (*RemoveUserStorageReq) ProtoMessage()    {}
func (*RemoveUserStorageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_datacache_65802314915f62bf, []int{3}
}
func (m *RemoveUserStorageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveUserStorageReq.Unmarshal(m, b)
}
func (m *RemoveUserStorageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveUserStorageReq.Marshal(b, m, deterministic)
}
func (dst *RemoveUserStorageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveUserStorageReq.Merge(dst, src)
}
func (m *RemoveUserStorageReq) XXX_Size() int {
	return xxx_messageInfo_RemoveUserStorageReq.Size(m)
}
func (m *RemoveUserStorageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveUserStorageReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveUserStorageReq proto.InternalMessageInfo

func (m *RemoveUserStorageReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RemoveUserStorageReq) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

func (m *RemoveUserStorageReq) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *RemoveUserStorageReq) GetSigMethod() string {
	if m != nil {
		return m.SigMethod
	}
	return ""
}

func (m *RemoveUserStorageReq) GetBody() *RemoveUserStorageReq_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type RemoveUserStorageReq_Body struct {
	Key                  []string `protobuf:"bytes,1,rep,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveUserStorageReq_Body) Reset()         { *m = RemoveUserStorageReq_Body{} }
func (m *RemoveUserStorageReq_Body) String() string { return proto.CompactTextString(m) }
func (*RemoveUserStorageReq_Body) ProtoMessage()    {}
func (*RemoveUserStorageReq_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_datacache_65802314915f62bf, []int{3, 0}
}
func (m *RemoveUserStorageReq_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveUserStorageReq_Body.Unmarshal(m, b)
}
func (m *RemoveUserStorageReq_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveUserStorageReq_Body.Marshal(b, m, deterministic)
}
func (dst *RemoveUserStorageReq_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveUserStorageReq_Body.Merge(dst, src)
}
func (m *RemoveUserStorageReq_Body) XXX_Size() int {
	return xxx_messageInfo_RemoveUserStorageReq_Body.Size(m)
}
func (m *RemoveUserStorageReq_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveUserStorageReq_Body.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveUserStorageReq_Body proto.InternalMessageInfo

func (m *RemoveUserStorageReq_Body) GetKey() []string {
	if m != nil {
		return m.Key
	}
	return nil
}

type RemoveUserStorageRes struct {
	Error                int64    `protobuf:"varint,1,opt,name=error" json:"error,omitempty"`
	Errcode              int64    `protobuf:"varint,2,opt,name=errcode" json:"errcode,omitempty"`
	Errmsg               string   `protobuf:"bytes,3,opt,name=errmsg" json:"errmsg,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveUserStorageRes) Reset()         { *m = RemoveUserStorageRes{} }
func (m *RemoveUserStorageRes) String() string { return proto.CompactTextString(m) }
func (*RemoveUserStorageRes) ProtoMessage()    {}
func (*RemoveUserStorageRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_datacache_65802314915f62bf, []int{4}
}
func (m *RemoveUserStorageRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveUserStorageRes.Unmarshal(m, b)
}
func (m *RemoveUserStorageRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveUserStorageRes.Marshal(b, m, deterministic)
}
func (dst *RemoveUserStorageRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveUserStorageRes.Merge(dst, src)
}
func (m *RemoveUserStorageRes) XXX_Size() int {
	return xxx_messageInfo_RemoveUserStorageRes.Size(m)
}
func (m *RemoveUserStorageRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveUserStorageRes.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveUserStorageRes proto.InternalMessageInfo

func (m *RemoveUserStorageRes) GetError() int64 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *RemoveUserStorageRes) GetErrcode() int64 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *RemoveUserStorageRes) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *RemoveUserStorageRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*KvItem)(nil), "developer.toutiao.com.KvItem")
	proto.RegisterType((*SetUserStorageReq)(nil), "developer.toutiao.com.SetUserStorageReq")
	proto.RegisterType((*SetUserStorageReq_Body)(nil), "developer.toutiao.com.SetUserStorageReq.Body")
	proto.RegisterType((*SetUserStorageRes)(nil), "developer.toutiao.com.SetUserStorageRes")
	proto.RegisterType((*RemoveUserStorageReq)(nil), "developer.toutiao.com.RemoveUserStorageReq")
	proto.RegisterType((*RemoveUserStorageReq_Body)(nil), "developer.toutiao.com.RemoveUserStorageReq.Body")
	proto.RegisterType((*RemoveUserStorageRes)(nil), "developer.toutiao.com.RemoveUserStorageRes")
}

func init() {
	proto.RegisterFile("douyin-miniapp/datacache.proto", fileDescriptor_datacache_65802314915f62bf)
}

var fileDescriptor_datacache_65802314915f62bf = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe5, 0x38, 0xa4, 0xea, 0x04, 0xa1, 0x76, 0x55, 0x90, 0x15, 0x35, 0x28, 0xac, 0x54,
	0x61, 0xa9, 0x8a, 0x5d, 0x05, 0x89, 0x03, 0x07, 0x24, 0xaa, 0x5e, 0x10, 0x70, 0x71, 0xe0, 0xc2,
	0xc5, 0xda, 0xd8, 0x23, 0x67, 0x95, 0xd8, 0x63, 0x76, 0xd7, 0x16, 0xb9, 0xf2, 0x00, 0xbd, 0x70,
	0xe3, 0x69, 0x78, 0x07, 0x5e, 0x81, 0x33, 0xcf, 0x80, 0xfc, 0x27, 0x2d, 0x51, 0x52, 0xa9, 0xbd,
	0xa0, 0xde, 0xfc, 0x8d, 0x67, 0x46, 0xb3, 0xbf, 0x6f, 0x76, 0xe1, 0x69, 0x4c, 0xc5, 0x4a, 0x66,
	0xe3, 0x54, 0x66, 0x52, 0xe4, 0xb9, 0x1f, 0x0b, 0x23, 0x22, 0x11, 0xcd, 0xd1, 0xcb, 0x15, 0x19,
	0x62, 0x8f, 0x63, 0x2c, 0x71, 0x49, 0x39, 0x2a, 0xcf, 0x50, 0x61, 0xa4, 0x20, 0x2f, 0xa2, 0x74,
	0x70, 0x9c, 0x10, 0x25, 0x4b, 0xf4, 0x45, 0x2e, 0x7d, 0x91, 0x65, 0x64, 0x84, 0x91, 0x94, 0xe9,
	0xa6, 0x88, 0x9f, 0x41, 0xef, 0x5d, 0xf9, 0xd6, 0x60, 0xca, 0x0e, 0xc0, 0x5e, 0xe0, 0xca, 0xb1,
	0x46, 0x96, 0xbb, 0x1f, 0x54, 0x9f, 0xec, 0x08, 0x1e, 0x94, 0x62, 0x59, 0xa0, 0xd3, 0xa9, 0x63,
	0x8d, 0xe0, 0x97, 0x1d, 0x38, 0x9c, 0xa2, 0xf9, 0xa4, 0x51, 0x4d, 0x0d, 0x29, 0x91, 0x60, 0x80,
	0x5f, 0xd8, 0x33, 0x78, 0x28, 0xa2, 0x08, 0xb5, 0x0e, 0x0d, 0x2d, 0x30, 0x6b, 0xdb, 0xf4, 0x9b,
	0xd8, 0xc7, 0x2a, 0xc4, 0x9e, 0x40, 0x8f, 0x72, 0xcc, 0x64, 0xdc, 0xf6, 0x6b, 0x15, 0x3b, 0x86,
	0x7d, 0x2d, 0x93, 0x4c, 0x98, 0x42, 0xa1, 0x63, 0xd7, 0xbf, 0xae, 0x03, 0x6c, 0x08, 0xa0, 0x65,
	0x12, 0xa6, 0x68, 0xe6, 0x14, 0x3b, 0xdd, 0xab, 0xdf, 0x1f, 0xea, 0x00, 0x7b, 0x03, 0xdd, 0x19,
	0xc5, 0x2b, 0x07, 0x46, 0x96, 0xdb, 0x9f, 0x8c, 0xbd, 0x9d, 0x0c, 0xbc, 0xad, 0x79, 0xbd, 0x73,
	0x8a, 0x57, 0x41, 0x5d, 0x3a, 0x78, 0x0d, 0xdd, 0x4a, 0xb1, 0x97, 0xb0, 0xb7, 0x28, 0xc3, 0xa5,
	0xd4, 0xc6, 0xb1, 0x46, 0xb6, 0xdb, 0x9f, 0x0c, 0x6f, 0xe8, 0xd6, 0x00, 0x0b, 0x7a, 0x8b, 0xf2,
	0xbd, 0xd4, 0x86, 0x17, 0xdb, 0x3c, 0x74, 0xc5, 0x0e, 0x95, 0x22, 0x55, 0x83, 0xb0, 0x83, 0x46,
	0x30, 0x07, 0xf6, 0x50, 0xa9, 0x88, 0xe2, 0x86, 0xa9, 0x1d, 0xac, 0x65, 0x05, 0x07, 0x95, 0x4a,
	0x75, 0xd2, 0x12, 0x68, 0x55, 0x55, 0x91, 0xa2, 0xd6, 0x22, 0xc1, 0xf6, 0xec, 0x6b, 0xc9, 0xff,
	0x58, 0x70, 0x14, 0x60, 0x4a, 0x25, 0xde, 0x13, 0x2b, 0x2e, 0x36, 0xac, 0x38, 0xbb, 0x01, 0xde,
	0xae, 0x91, 0xff, 0x75, 0xc3, 0x69, 0xdd, 0xb8, 0x5a, 0x47, 0xbb, 0x5d, 0x47, 0xfe, 0x75, 0xe7,
	0x79, 0xff, 0x03, 0xea, 0xc9, 0xcf, 0x0e, 0x1c, 0x5c, 0xac, 0x6f, 0xdb, 0x14, 0x55, 0x29, 0x23,
	0x64, 0x97, 0x16, 0x3c, 0xda, 0xf4, 0x9d, 0xb9, 0xb7, 0x5d, 0xbf, 0xc1, 0x6d, 0x33, 0x35, 0x77,
	0xbf, 0xfd, 0xfa, 0xfd, 0xbd, 0xc3, 0xf9, 0xa0, 0xb9, 0xc0, 0x79, 0xae, 0x7d, 0x8d, 0x26, 0x2c,
	0x34, 0xaa, 0x50, 0x37, 0x69, 0xaf, 0x6a, 0x72, 0xec, 0x87, 0x05, 0x87, 0x5b, 0x80, 0xd8, 0xe9,
	0x1d, 0x7c, 0x18, 0xdc, 0x21, 0x59, 0xf3, 0xd3, 0x7a, 0xb2, 0x13, 0x3e, 0xbc, 0x9e, 0x4c, 0xd5,
	0x79, 0x3b, 0x86, 0x3b, 0x7f, 0xfe, 0xf9, 0x24, 0x91, 0x66, 0x5e, 0xcc, 0xaa, 0x7e, 0x7e, 0x8c,
	0xe5, 0xb8, 0x5a, 0xb9, 0xaa, 0x70, 0xf3, 0x55, 0x9b, 0xf5, 0xea, 0x77, 0xe9, 0xc5, 0xdf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xbd, 0xcf, 0x80, 0x7a, 0xee, 0x04, 0x00, 0x00,
}
