// 抖音小程序开放接口-数据缓存 douyin-miniapp

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.0
// source: douyin-miniapp/datacache.proto

package douyin_miniapp

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KvItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // 键
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // 值
}

func (x *KvItem) Reset() {
	*x = KvItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_douyin_miniapp_datacache_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KvItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvItem) ProtoMessage() {}

func (x *KvItem) ProtoReflect() protoreflect.Message {
	mi := &file_douyin_miniapp_datacache_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvItem.ProtoReflect.Descriptor instead.
func (*KvItem) Descriptor() ([]byte, []int) {
	return file_douyin_miniapp_datacache_proto_rawDescGZIP(), []int{0}
}

func (x *KvItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KvItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetUserStorageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string                  `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // 服务端 API 调用标识，获取方法
	Openid      string                  `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid,omitempty"`                              // 登录用户唯一标识 获取方法
	Signature   string                  `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                        // 用户登录态签名，参考用户登录态签名算法
	SigMethod   string                  `protobuf:"bytes,4,opt,name=sig_method,json=sigMethod,proto3" json:"sig_method,omitempty"`       // 用户登录态签名的编码方法，参考用户登录态签名算法
	Body        *SetUserStorageReq_Body `protobuf:"bytes,10,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *SetUserStorageReq) Reset() {
	*x = SetUserStorageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_douyin_miniapp_datacache_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserStorageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserStorageReq) ProtoMessage() {}

func (x *SetUserStorageReq) ProtoReflect() protoreflect.Message {
	mi := &file_douyin_miniapp_datacache_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserStorageReq.ProtoReflect.Descriptor instead.
func (*SetUserStorageReq) Descriptor() ([]byte, []int) {
	return file_douyin_miniapp_datacache_proto_rawDescGZIP(), []int{1}
}

func (x *SetUserStorageReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SetUserStorageReq) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *SetUserStorageReq) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SetUserStorageReq) GetSigMethod() string {
	if x != nil {
		return x.SigMethod
	}
	return ""
}

func (x *SetUserStorageReq) GetBody() *SetUserStorageReq_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type SetUserStorageRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   int64  `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`     // 错误号, 正确返回时为 0
	Errcode int64  `protobuf:"varint,2,opt,name=errcode,proto3" json:"errcode,omitempty"` // 详细错误号
	Errmsg  string `protobuf:"bytes,3,opt,name=errmsg,proto3" json:"errmsg,omitempty"`    // 错误信息
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`  // 错误信息（同 errmsg）
}

func (x *SetUserStorageRes) Reset() {
	*x = SetUserStorageRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_douyin_miniapp_datacache_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserStorageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserStorageRes) ProtoMessage() {}

func (x *SetUserStorageRes) ProtoReflect() protoreflect.Message {
	mi := &file_douyin_miniapp_datacache_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserStorageRes.ProtoReflect.Descriptor instead.
func (*SetUserStorageRes) Descriptor() ([]byte, []int) {
	return file_douyin_miniapp_datacache_proto_rawDescGZIP(), []int{2}
}

func (x *SetUserStorageRes) GetError() int64 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *SetUserStorageRes) GetErrcode() int64 {
	if x != nil {
		return x.Errcode
	}
	return 0
}

func (x *SetUserStorageRes) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *SetUserStorageRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveUserStorageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string                     `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // 服务端 API 调用标识，获取方法
	Openid      string                     `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid,omitempty"`                              // 登录用户唯一标识 获取方法
	Signature   string                     `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                        // 用户登录态签名，参考用户登录态签名算法
	SigMethod   string                     `protobuf:"bytes,4,opt,name=sig_method,json=sigMethod,proto3" json:"sig_method,omitempty"`       // 用户登录态签名的编码方法，参考用户登录态签名算法
	Body        *RemoveUserStorageReq_Body `protobuf:"bytes,10,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *RemoveUserStorageReq) Reset() {
	*x = RemoveUserStorageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_douyin_miniapp_datacache_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveUserStorageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserStorageReq) ProtoMessage() {}

func (x *RemoveUserStorageReq) ProtoReflect() protoreflect.Message {
	mi := &file_douyin_miniapp_datacache_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserStorageReq.ProtoReflect.Descriptor instead.
func (*RemoveUserStorageReq) Descriptor() ([]byte, []int) {
	return file_douyin_miniapp_datacache_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveUserStorageReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RemoveUserStorageReq) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *RemoveUserStorageReq) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *RemoveUserStorageReq) GetSigMethod() string {
	if x != nil {
		return x.SigMethod
	}
	return ""
}

func (x *RemoveUserStorageReq) GetBody() *RemoveUserStorageReq_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type RemoveUserStorageRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   int64  `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`     // 错误号, 正确返回时为 0
	Errcode int64  `protobuf:"varint,2,opt,name=errcode,proto3" json:"errcode,omitempty"` // 详细错误号
	Errmsg  string `protobuf:"bytes,3,opt,name=errmsg,proto3" json:"errmsg,omitempty"`    // 错误信息
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`  // 错误信息（同 errmsg）
}

func (x *RemoveUserStorageRes) Reset() {
	*x = RemoveUserStorageRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_douyin_miniapp_datacache_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveUserStorageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserStorageRes) ProtoMessage() {}

func (x *RemoveUserStorageRes) ProtoReflect() protoreflect.Message {
	mi := &file_douyin_miniapp_datacache_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserStorageRes.ProtoReflect.Descriptor instead.
func (*RemoveUserStorageRes) Descriptor() ([]byte, []int) {
	return file_douyin_miniapp_datacache_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveUserStorageRes) GetError() int64 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *RemoveUserStorageRes) GetErrcode() int64 {
	if x != nil {
		return x.Errcode
	}
	return 0
}

func (x *RemoveUserStorageRes) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *RemoveUserStorageRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SetUserStorageReq_Body struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KvList []*KvItem `protobuf:"bytes,1,rep,name=kv_list,json=kvList,proto3" json:"kv_list,omitempty"` // (body 中) 要设置的用户数据
}

func (x *SetUserStorageReq_Body) Reset() {
	*x = SetUserStorageReq_Body{}
	if protoimpl.UnsafeEnabled {
		mi := &file_douyin_miniapp_datacache_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUserStorageReq_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserStorageReq_Body) ProtoMessage() {}

func (x *SetUserStorageReq_Body) ProtoReflect() protoreflect.Message {
	mi := &file_douyin_miniapp_datacache_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserStorageReq_Body.ProtoReflect.Descriptor instead.
func (*SetUserStorageReq_Body) Descriptor() ([]byte, []int) {
	return file_douyin_miniapp_datacache_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SetUserStorageReq_Body) GetKvList() []*KvItem {
	if x != nil {
		return x.KvList
	}
	return nil
}

type RemoveUserStorageReq_Body struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []string `protobuf:"bytes,1,rep,name=key,proto3" json:"key,omitempty"` // (body 中) 要删除的用户数据的 key list
}

func (x *RemoveUserStorageReq_Body) Reset() {
	*x = RemoveUserStorageReq_Body{}
	if protoimpl.UnsafeEnabled {
		mi := &file_douyin_miniapp_datacache_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveUserStorageReq_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserStorageReq_Body) ProtoMessage() {}

func (x *RemoveUserStorageReq_Body) ProtoReflect() protoreflect.Message {
	mi := &file_douyin_miniapp_datacache_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserStorageReq_Body.ProtoReflect.Descriptor instead.
func (*RemoveUserStorageReq_Body) Descriptor() ([]byte, []int) {
	return file_douyin_miniapp_datacache_proto_rawDescGZIP(), []int{3, 0}
}

func (x *RemoveUserStorageReq_Body) GetKey() []string {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_douyin_miniapp_datacache_proto protoreflect.FileDescriptor

var file_douyin_miniapp_datacache_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2d, 0x6d, 0x69, 0x6e, 0x69, 0x61, 0x70, 0x70,
	0x2f, 0x64, 0x61, 0x74, 0x61, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x15, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x74, 0x6f, 0x75, 0x74,
	0x69, 0x61, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x06, 0x4b, 0x76, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x8e, 0x02, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a,
	0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x69, 0x67, 0x5f, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x41, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x2e,
	0x74, 0x6f, 0x75, 0x74, 0x69, 0x61, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x53, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x42, 0x6f,
	0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x1a, 0x3e, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79,
	0x12, 0x36, 0x0a, 0x07, 0x6b, 0x76, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x74, 0x6f,
	0x75, 0x74, 0x69, 0x61, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x4b, 0x76, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x06, 0x6b, 0x76, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x75, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65,
	0x72, 0x72, 0x6d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0xee, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65,
	0x6e, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x69, 0x67, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x12, 0x44, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30,
	0x2e, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x74, 0x6f, 0x75, 0x74, 0x69,
	0x61, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x42, 0x6f, 0x64, 0x79,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x1a, 0x18, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x78, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d,
	0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xc0, 0x02, 0x0a, 0x10, 0x44,
	0x61, 0x74, 0x61, 0x63, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x8e, 0x01, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x12, 0x28, 0x2e, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x74,
	0x6f, 0x75, 0x74, 0x69, 0x61, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x28, 0x2e, 0x64,
	0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x74, 0x6f, 0x75, 0x74, 0x69, 0x61, 0x6f,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x22, 0x28, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x22, 0x22, 0x1a,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x73, 0x65, 0x74, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x3a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x12, 0x9a, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x2e, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x65, 0x72, 0x2e, 0x74, 0x6f, 0x75, 0x74, 0x69, 0x61, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x2b, 0x2e, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x2e,
	0x74, 0x6f, 0x75, 0x74, 0x69, 0x61, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x22, 0x2b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x25, 0x22, 0x1d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x70, 0x70, 0x73, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x3a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x42, 0x27, 0x5a,
	0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x76, 0x2d,
	0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2d, 0x6d,
	0x69, 0x6e, 0x69, 0x61, 0x70, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_douyin_miniapp_datacache_proto_rawDescOnce sync.Once
	file_douyin_miniapp_datacache_proto_rawDescData = file_douyin_miniapp_datacache_proto_rawDesc
)

func file_douyin_miniapp_datacache_proto_rawDescGZIP() []byte {
	file_douyin_miniapp_datacache_proto_rawDescOnce.Do(func() {
		file_douyin_miniapp_datacache_proto_rawDescData = protoimpl.X.CompressGZIP(file_douyin_miniapp_datacache_proto_rawDescData)
	})
	return file_douyin_miniapp_datacache_proto_rawDescData
}

var file_douyin_miniapp_datacache_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_douyin_miniapp_datacache_proto_goTypes = []interface{}{
	(*KvItem)(nil),                    // 0: developer.toutiao.com.KvItem
	(*SetUserStorageReq)(nil),         // 1: developer.toutiao.com.SetUserStorageReq
	(*SetUserStorageRes)(nil),         // 2: developer.toutiao.com.SetUserStorageRes
	(*RemoveUserStorageReq)(nil),      // 3: developer.toutiao.com.RemoveUserStorageReq
	(*RemoveUserStorageRes)(nil),      // 4: developer.toutiao.com.RemoveUserStorageRes
	(*SetUserStorageReq_Body)(nil),    // 5: developer.toutiao.com.SetUserStorageReq.Body
	(*RemoveUserStorageReq_Body)(nil), // 6: developer.toutiao.com.RemoveUserStorageReq.Body
}
var file_douyin_miniapp_datacache_proto_depIdxs = []int32{
	5, // 0: developer.toutiao.com.SetUserStorageReq.body:type_name -> developer.toutiao.com.SetUserStorageReq.Body
	6, // 1: developer.toutiao.com.RemoveUserStorageReq.body:type_name -> developer.toutiao.com.RemoveUserStorageReq.Body
	0, // 2: developer.toutiao.com.SetUserStorageReq.Body.kv_list:type_name -> developer.toutiao.com.KvItem
	1, // 3: developer.toutiao.com.DatacacheService.SetUserStorage:input_type -> developer.toutiao.com.SetUserStorageReq
	3, // 4: developer.toutiao.com.DatacacheService.RemoveUserStorage:input_type -> developer.toutiao.com.RemoveUserStorageReq
	2, // 5: developer.toutiao.com.DatacacheService.SetUserStorage:output_type -> developer.toutiao.com.SetUserStorageRes
	4, // 6: developer.toutiao.com.DatacacheService.RemoveUserStorage:output_type -> developer.toutiao.com.RemoveUserStorageRes
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_douyin_miniapp_datacache_proto_init() }
func file_douyin_miniapp_datacache_proto_init() {
	if File_douyin_miniapp_datacache_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_douyin_miniapp_datacache_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KvItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_douyin_miniapp_datacache_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserStorageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_douyin_miniapp_datacache_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserStorageRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_douyin_miniapp_datacache_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveUserStorageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_douyin_miniapp_datacache_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveUserStorageRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_douyin_miniapp_datacache_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUserStorageReq_Body); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_douyin_miniapp_datacache_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveUserStorageReq_Body); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_douyin_miniapp_datacache_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_douyin_miniapp_datacache_proto_goTypes,
		DependencyIndexes: file_douyin_miniapp_datacache_proto_depIdxs,
		MessageInfos:      file_douyin_miniapp_datacache_proto_msgTypes,
	}.Build()
	File_douyin_miniapp_datacache_proto = out.File
	file_douyin_miniapp_datacache_proto_rawDesc = nil
	file_douyin_miniapp_datacache_proto_goTypes = nil
	file_douyin_miniapp_datacache_proto_depIdxs = nil
}
