// Code generated by protoc-gen-go. DO NOT EDIT.
// source: douyin-miniapp/ecom.proto

package douyin_miniapp // import "github.com/dev-openapi/douyin-miniapp"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterInfoReq struct {
	Body                 *RegisterInfoReq_Body `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RegisterInfoReq) Reset()         { *m = RegisterInfoReq{} }
func (m *RegisterInfoReq) String() string { return proto.CompactTextString(m) }
func (*RegisterInfoReq) ProtoMessage()    {}
func (*RegisterInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecom_7e7cc04ffc69f395, []int{0}
}
func (m *RegisterInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterInfoReq.Unmarshal(m, b)
}
func (m *RegisterInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterInfoReq.Marshal(b, m, deterministic)
}
func (dst *RegisterInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterInfoReq.Merge(dst, src)
}
func (m *RegisterInfoReq) XXX_Size() int {
	return xxx_messageInfo_RegisterInfoReq.Size(m)
}
func (m *RegisterInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterInfoReq proto.InternalMessageInfo

func (m *RegisterInfoReq) GetBody() *RegisterInfoReq_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type RegisterInfoReq_Body struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	EcomMicroappType     int32    `protobuf:"varint,3,opt,name=ecom_microapp_type,json=ecomMicroappType" json:"ecom_microapp_type,omitempty"`
	PreViewPhotoUrl      string   `protobuf:"bytes,4,opt,name=pre_view_photo_url,json=preViewPhotoUrl" json:"pre_view_photo_url,omitempty"`
	Extra                string   `protobuf:"bytes,5,opt,name=extra" json:"extra,omitempty"`
	CallbackUrl          string   `protobuf:"bytes,6,opt,name=callback_url,json=callbackUrl" json:"callback_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterInfoReq_Body) Reset()         { *m = RegisterInfoReq_Body{} }
func (m *RegisterInfoReq_Body) String() string { return proto.CompactTextString(m) }
func (*RegisterInfoReq_Body) ProtoMessage()    {}
func (*RegisterInfoReq_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecom_7e7cc04ffc69f395, []int{0, 0}
}
func (m *RegisterInfoReq_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterInfoReq_Body.Unmarshal(m, b)
}
func (m *RegisterInfoReq_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterInfoReq_Body.Marshal(b, m, deterministic)
}
func (dst *RegisterInfoReq_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterInfoReq_Body.Merge(dst, src)
}
func (m *RegisterInfoReq_Body) XXX_Size() int {
	return xxx_messageInfo_RegisterInfoReq_Body.Size(m)
}
func (m *RegisterInfoReq_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterInfoReq_Body.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterInfoReq_Body proto.InternalMessageInfo

func (m *RegisterInfoReq_Body) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RegisterInfoReq_Body) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *RegisterInfoReq_Body) GetEcomMicroappType() int32 {
	if m != nil {
		return m.EcomMicroappType
	}
	return 0
}

func (m *RegisterInfoReq_Body) GetPreViewPhotoUrl() string {
	if m != nil {
		return m.PreViewPhotoUrl
	}
	return ""
}

func (m *RegisterInfoReq_Body) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func (m *RegisterInfoReq_Body) GetCallbackUrl() string {
	if m != nil {
		return m.CallbackUrl
	}
	return ""
}

type RegisterInfoRes struct {
	ErrNo                int32    `protobuf:"varint,1,opt,name=err_no,json=errNo" json:"err_no,omitempty"`
	ErrTips              string   `protobuf:"bytes,2,opt,name=err_tips,json=errTips" json:"err_tips,omitempty"`
	LogId                string   `protobuf:"bytes,3,opt,name=log_id,json=logId" json:"log_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterInfoRes) Reset()         { *m = RegisterInfoRes{} }
func (m *RegisterInfoRes) String() string { return proto.CompactTextString(m) }
func (*RegisterInfoRes) ProtoMessage()    {}
func (*RegisterInfoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecom_7e7cc04ffc69f395, []int{1}
}
func (m *RegisterInfoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterInfoRes.Unmarshal(m, b)
}
func (m *RegisterInfoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterInfoRes.Marshal(b, m, deterministic)
}
func (dst *RegisterInfoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterInfoRes.Merge(dst, src)
}
func (m *RegisterInfoRes) XXX_Size() int {
	return xxx_messageInfo_RegisterInfoRes.Size(m)
}
func (m *RegisterInfoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterInfoRes.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterInfoRes proto.InternalMessageInfo

func (m *RegisterInfoRes) GetErrNo() int32 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *RegisterInfoRes) GetErrTips() string {
	if m != nil {
		return m.ErrTips
	}
	return ""
}

func (m *RegisterInfoRes) GetLogId() string {
	if m != nil {
		return m.LogId
	}
	return ""
}

type PointLimitRegisterReq struct {
	Body                 *PointLimitRegisterReq_Body `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *PointLimitRegisterReq) Reset()         { *m = PointLimitRegisterReq{} }
func (m *PointLimitRegisterReq) String() string { return proto.CompactTextString(m) }
func (*PointLimitRegisterReq) ProtoMessage()    {}
func (*PointLimitRegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecom_7e7cc04ffc69f395, []int{2}
}
func (m *PointLimitRegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointLimitRegisterReq.Unmarshal(m, b)
}
func (m *PointLimitRegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointLimitRegisterReq.Marshal(b, m, deterministic)
}
func (dst *PointLimitRegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointLimitRegisterReq.Merge(dst, src)
}
func (m *PointLimitRegisterReq) XXX_Size() int {
	return xxx_messageInfo_PointLimitRegisterReq.Size(m)
}
func (m *PointLimitRegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PointLimitRegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_PointLimitRegisterReq proto.InternalMessageInfo

func (m *PointLimitRegisterReq) GetBody() *PointLimitRegisterReq_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type PointLimitRegisterReq_Body struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	OpType               string   `protobuf:"bytes,3,opt,name=op_type,json=opType" json:"op_type,omitempty"`
	SingleAddLimit       int64    `protobuf:"varint,4,opt,name=single_add_limit,json=singleAddLimit" json:"single_add_limit,omitempty"`
	SingleReductLimit    int64    `protobuf:"varint,5,opt,name=single_reduct_limit,json=singleReductLimit" json:"single_reduct_limit,omitempty"`
	DailyAddCount        int64    `protobuf:"varint,6,opt,name=daily_add_count,json=dailyAddCount" json:"daily_add_count,omitempty"`
	DailyDeductCount     int64    `protobuf:"varint,7,opt,name=daily_deduct_count,json=dailyDeductCount" json:"daily_deduct_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointLimitRegisterReq_Body) Reset()         { *m = PointLimitRegisterReq_Body{} }
func (m *PointLimitRegisterReq_Body) String() string { return proto.CompactTextString(m) }
func (*PointLimitRegisterReq_Body) ProtoMessage()    {}
func (*PointLimitRegisterReq_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecom_7e7cc04ffc69f395, []int{2, 0}
}
func (m *PointLimitRegisterReq_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointLimitRegisterReq_Body.Unmarshal(m, b)
}
func (m *PointLimitRegisterReq_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointLimitRegisterReq_Body.Marshal(b, m, deterministic)
}
func (dst *PointLimitRegisterReq_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointLimitRegisterReq_Body.Merge(dst, src)
}
func (m *PointLimitRegisterReq_Body) XXX_Size() int {
	return xxx_messageInfo_PointLimitRegisterReq_Body.Size(m)
}
func (m *PointLimitRegisterReq_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_PointLimitRegisterReq_Body.DiscardUnknown(m)
}

var xxx_messageInfo_PointLimitRegisterReq_Body proto.InternalMessageInfo

func (m *PointLimitRegisterReq_Body) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *PointLimitRegisterReq_Body) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *PointLimitRegisterReq_Body) GetOpType() string {
	if m != nil {
		return m.OpType
	}
	return ""
}

func (m *PointLimitRegisterReq_Body) GetSingleAddLimit() int64 {
	if m != nil {
		return m.SingleAddLimit
	}
	return 0
}

func (m *PointLimitRegisterReq_Body) GetSingleReductLimit() int64 {
	if m != nil {
		return m.SingleReductLimit
	}
	return 0
}

func (m *PointLimitRegisterReq_Body) GetDailyAddCount() int64 {
	if m != nil {
		return m.DailyAddCount
	}
	return 0
}

func (m *PointLimitRegisterReq_Body) GetDailyDeductCount() int64 {
	if m != nil {
		return m.DailyDeductCount
	}
	return 0
}

type PointLimitRegisterRes struct {
	ErrNo                int32    `protobuf:"varint,1,opt,name=err_no,json=errNo" json:"err_no,omitempty"`
	ErrTips              string   `protobuf:"bytes,2,opt,name=err_tips,json=errTips" json:"err_tips,omitempty"`
	LogId                string   `protobuf:"bytes,3,opt,name=log_id,json=logId" json:"log_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointLimitRegisterRes) Reset()         { *m = PointLimitRegisterRes{} }
func (m *PointLimitRegisterRes) String() string { return proto.CompactTextString(m) }
func (*PointLimitRegisterRes) ProtoMessage()    {}
func (*PointLimitRegisterRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecom_7e7cc04ffc69f395, []int{3}
}
func (m *PointLimitRegisterRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointLimitRegisterRes.Unmarshal(m, b)
}
func (m *PointLimitRegisterRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointLimitRegisterRes.Marshal(b, m, deterministic)
}
func (dst *PointLimitRegisterRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointLimitRegisterRes.Merge(dst, src)
}
func (m *PointLimitRegisterRes) XXX_Size() int {
	return xxx_messageInfo_PointLimitRegisterRes.Size(m)
}
func (m *PointLimitRegisterRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PointLimitRegisterRes.DiscardUnknown(m)
}

var xxx_messageInfo_PointLimitRegisterRes proto.InternalMessageInfo

func (m *PointLimitRegisterRes) GetErrNo() int32 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *PointLimitRegisterRes) GetErrTips() string {
	if m != nil {
		return m.ErrTips
	}
	return ""
}

func (m *PointLimitRegisterRes) GetLogId() string {
	if m != nil {
		return m.LogId
	}
	return ""
}

type GetCustomMadeGoodsStatusReq struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	OpenId               string   `protobuf:"bytes,2,opt,name=open_id,json=openId" json:"open_id,omitempty"`
	OrderId              string   `protobuf:"bytes,3,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomMadeGoodsStatusReq) Reset()         { *m = GetCustomMadeGoodsStatusReq{} }
func (m *GetCustomMadeGoodsStatusReq) String() string { return proto.CompactTextString(m) }
func (*GetCustomMadeGoodsStatusReq) ProtoMessage()    {}
func (*GetCustomMadeGoodsStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecom_7e7cc04ffc69f395, []int{4}
}
func (m *GetCustomMadeGoodsStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomMadeGoodsStatusReq.Unmarshal(m, b)
}
func (m *GetCustomMadeGoodsStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomMadeGoodsStatusReq.Marshal(b, m, deterministic)
}
func (dst *GetCustomMadeGoodsStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomMadeGoodsStatusReq.Merge(dst, src)
}
func (m *GetCustomMadeGoodsStatusReq) XXX_Size() int {
	return xxx_messageInfo_GetCustomMadeGoodsStatusReq.Size(m)
}
func (m *GetCustomMadeGoodsStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomMadeGoodsStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomMadeGoodsStatusReq proto.InternalMessageInfo

func (m *GetCustomMadeGoodsStatusReq) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *GetCustomMadeGoodsStatusReq) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *GetCustomMadeGoodsStatusReq) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type GetCustomMadeGoodsStatusRes struct {
	ErrNo                int32    `protobuf:"varint,1,opt,name=err_no,json=errNo" json:"err_no,omitempty"`
	ErrTips              string   `protobuf:"bytes,2,opt,name=err_tips,json=errTips" json:"err_tips,omitempty"`
	LogId                string   `protobuf:"bytes,3,opt,name=log_id,json=logId" json:"log_id,omitempty"`
	SuccessCode          int32    `protobuf:"varint,4,opt,name=success_code,json=successCode" json:"success_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomMadeGoodsStatusRes) Reset()         { *m = GetCustomMadeGoodsStatusRes{} }
func (m *GetCustomMadeGoodsStatusRes) String() string { return proto.CompactTextString(m) }
func (*GetCustomMadeGoodsStatusRes) ProtoMessage()    {}
func (*GetCustomMadeGoodsStatusRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecom_7e7cc04ffc69f395, []int{5}
}
func (m *GetCustomMadeGoodsStatusRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomMadeGoodsStatusRes.Unmarshal(m, b)
}
func (m *GetCustomMadeGoodsStatusRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomMadeGoodsStatusRes.Marshal(b, m, deterministic)
}
func (dst *GetCustomMadeGoodsStatusRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomMadeGoodsStatusRes.Merge(dst, src)
}
func (m *GetCustomMadeGoodsStatusRes) XXX_Size() int {
	return xxx_messageInfo_GetCustomMadeGoodsStatusRes.Size(m)
}
func (m *GetCustomMadeGoodsStatusRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomMadeGoodsStatusRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomMadeGoodsStatusRes proto.InternalMessageInfo

func (m *GetCustomMadeGoodsStatusRes) GetErrNo() int32 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *GetCustomMadeGoodsStatusRes) GetErrTips() string {
	if m != nil {
		return m.ErrTips
	}
	return ""
}

func (m *GetCustomMadeGoodsStatusRes) GetLogId() string {
	if m != nil {
		return m.LogId
	}
	return ""
}

func (m *GetCustomMadeGoodsStatusRes) GetSuccessCode() int32 {
	if m != nil {
		return m.SuccessCode
	}
	return 0
}

type LeaveMemberReq struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	ShopId               int64    `protobuf:"varint,2,opt,name=shop_id,json=shopId" json:"shop_id,omitempty"`
	OpenId               string   `protobuf:"bytes,3,opt,name=open_id,json=openId" json:"open_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveMemberReq) Reset()         { *m = LeaveMemberReq{} }
func (m *LeaveMemberReq) String() string { return proto.CompactTextString(m) }
func (*LeaveMemberReq) ProtoMessage()    {}
func (*LeaveMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecom_7e7cc04ffc69f395, []int{6}
}
func (m *LeaveMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveMemberReq.Unmarshal(m, b)
}
func (m *LeaveMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveMemberReq.Marshal(b, m, deterministic)
}
func (dst *LeaveMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveMemberReq.Merge(dst, src)
}
func (m *LeaveMemberReq) XXX_Size() int {
	return xxx_messageInfo_LeaveMemberReq.Size(m)
}
func (m *LeaveMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveMemberReq proto.InternalMessageInfo

func (m *LeaveMemberReq) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *LeaveMemberReq) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *LeaveMemberReq) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

type LeaveMemberRes struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	OpenId               string   `protobuf:"bytes,2,opt,name=open_id,json=openId" json:"open_id,omitempty"`
	OrderId              string   `protobuf:"bytes,3,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveMemberRes) Reset()         { *m = LeaveMemberRes{} }
func (m *LeaveMemberRes) String() string { return proto.CompactTextString(m) }
func (*LeaveMemberRes) ProtoMessage()    {}
func (*LeaveMemberRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecom_7e7cc04ffc69f395, []int{7}
}
func (m *LeaveMemberRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveMemberRes.Unmarshal(m, b)
}
func (m *LeaveMemberRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveMemberRes.Marshal(b, m, deterministic)
}
func (dst *LeaveMemberRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveMemberRes.Merge(dst, src)
}
func (m *LeaveMemberRes) XXX_Size() int {
	return xxx_messageInfo_LeaveMemberRes.Size(m)
}
func (m *LeaveMemberRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveMemberRes.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveMemberRes proto.InternalMessageInfo

func (m *LeaveMemberRes) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *LeaveMemberRes) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *LeaveMemberRes) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterInfoReq)(nil), "ma.zijieapi.com.RegisterInfoReq")
	proto.RegisterType((*RegisterInfoReq_Body)(nil), "ma.zijieapi.com.RegisterInfoReq.Body")
	proto.RegisterType((*RegisterInfoRes)(nil), "ma.zijieapi.com.RegisterInfoRes")
	proto.RegisterType((*PointLimitRegisterReq)(nil), "ma.zijieapi.com.PointLimitRegisterReq")
	proto.RegisterType((*PointLimitRegisterReq_Body)(nil), "ma.zijieapi.com.PointLimitRegisterReq.Body")
	proto.RegisterType((*PointLimitRegisterRes)(nil), "ma.zijieapi.com.PointLimitRegisterRes")
	proto.RegisterType((*GetCustomMadeGoodsStatusReq)(nil), "ma.zijieapi.com.GetCustomMadeGoodsStatusReq")
	proto.RegisterType((*GetCustomMadeGoodsStatusRes)(nil), "ma.zijieapi.com.GetCustomMadeGoodsStatusRes")
	proto.RegisterType((*LeaveMemberReq)(nil), "ma.zijieapi.com.LeaveMemberReq")
	proto.RegisterType((*LeaveMemberRes)(nil), "ma.zijieapi.com.LeaveMemberRes")
}

func init() { proto.RegisterFile("douyin-miniapp/ecom.proto", fileDescriptor_ecom_7e7cc04ffc69f395) }

var fileDescriptor_ecom_7e7cc04ffc69f395 = []byte{
	// 811 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xd6, 0xda, 0x5e, 0x9b, 0x8e, 0x4b, 0x1d, 0x06, 0x2a, 0x5c, 0x83, 0x44, 0x58, 0x29, 0x25,
	0x6a, 0x13, 0xaf, 0xfa, 0x23, 0xa1, 0xfa, 0xa6, 0x6a, 0x03, 0xaa, 0x2c, 0x35, 0xa8, 0xda, 0xa6,
	0x48, 0x94, 0x8b, 0x65, 0xbc, 0x73, 0xba, 0x1e, 0xba, 0xbb, 0x67, 0x98, 0x99, 0x75, 0x31, 0x97,
	0xdc, 0x40, 0xaf, 0x79, 0x01, 0x24, 0x1e, 0x82, 0x07, 0x81, 0x47, 0xc8, 0x7b, 0x80, 0x66, 0xd6,
	0x49, 0xfc, 0x13, 0x27, 0x41, 0xe4, 0x72, 0xce, 0xf9, 0xce, 0x99, 0xef, 0x7c, 0xe7, 0x9b, 0x5d,
	0x72, 0x83, 0x63, 0x39, 0x15, 0xc5, 0x6e, 0x2e, 0x0a, 0xc1, 0xa4, 0x0c, 0x21, 0xc1, 0xbc, 0x2f,
	0x15, 0x1a, 0xa4, 0x9d, 0x9c, 0xf5, 0x7f, 0x12, 0xdf, 0x0b, 0x60, 0x52, 0xf4, 0x13, 0xcc, 0x7b,
	0x1f, 0xa7, 0x88, 0x69, 0x06, 0x21, 0x93, 0x22, 0x64, 0x45, 0x81, 0x86, 0x19, 0x81, 0x85, 0xae,
	0xe0, 0xc1, 0x1f, 0x35, 0xd2, 0x89, 0x20, 0x15, 0xda, 0x80, 0x1a, 0x16, 0xaf, 0x30, 0x82, 0x1f,
	0xe8, 0x03, 0xd2, 0x18, 0x21, 0x9f, 0x76, 0xbd, 0x4d, 0x6f, 0xbb, 0x7d, 0x77, 0xab, 0xbf, 0xd4,
	0xb1, 0xbf, 0x84, 0xef, 0x3f, 0x46, 0x3e, 0x8d, 0x5c, 0x49, 0xef, 0x6f, 0x8f, 0x34, 0xec, 0x91,
	0x7e, 0x4a, 0xae, 0xb2, 0x24, 0x01, 0xad, 0x63, 0x83, 0xaf, 0xa1, 0x70, 0xbd, 0xae, 0x44, 0xed,
	0x2a, 0x76, 0x60, 0x43, 0xf4, 0x3a, 0x69, 0x32, 0x29, 0x63, 0xc1, 0xbb, 0x35, 0x97, 0xf4, 0x99,
	0x94, 0x43, 0x4e, 0x77, 0x08, 0xb5, 0xe3, 0xc4, 0xb9, 0x48, 0x14, 0x5a, 0x80, 0x99, 0x4a, 0xe8,
	0xd6, 0x37, 0xbd, 0x6d, 0x3f, 0xda, 0xb0, 0x99, 0xfd, 0x59, 0xe2, 0x60, 0x2a, 0x81, 0xde, 0x26,
	0x54, 0x2a, 0x88, 0x27, 0x02, 0xde, 0xc4, 0x72, 0x8c, 0x06, 0xe3, 0x52, 0x65, 0xdd, 0x86, 0x6b,
	0xd8, 0x91, 0x0a, 0xbe, 0x16, 0xf0, 0xe6, 0x99, 0x8d, 0xbf, 0x50, 0x19, 0xfd, 0x80, 0xf8, 0xf0,
	0xa3, 0x51, 0xac, 0xeb, 0x57, 0x17, 0xba, 0x83, 0xa5, 0x9a, 0xb0, 0x2c, 0x1b, 0xb1, 0xe4, 0xb5,
	0x2b, 0x6e, 0x56, 0x54, 0x8f, 0x62, 0x2f, 0x54, 0x16, 0xbc, 0x5c, 0x16, 0x49, 0x5b, 0xf6, 0xa0,
	0x54, 0x5c, 0xa0, 0x1b, 0xcd, 0x8f, 0x7c, 0x50, 0xea, 0x2b, 0xa4, 0x37, 0xc8, 0x3b, 0x36, 0x6c,
	0x84, 0xd4, 0xb3, 0xb1, 0x5a, 0xa0, 0xd4, 0x81, 0x90, 0xae, 0x22, 0xc3, 0xd4, 0xce, 0x5b, 0xaf,
	0xae, 0xcf, 0x30, 0x1d, 0xf2, 0xe0, 0xb0, 0x46, 0xae, 0x3f, 0x43, 0x51, 0x98, 0xa7, 0x22, 0x17,
	0xe6, 0xe8, 0x1a, 0xbb, 0x87, 0x87, 0x0b, 0x7b, 0xb8, 0xbd, 0xb2, 0x87, 0x53, 0xab, 0xe6, 0xb7,
	0xf1, 0xb6, 0xf6, 0xbf, 0xb7, 0xf1, 0x21, 0x69, 0xe1, 0xdc, 0x0a, 0xae, 0x44, 0x4d, 0xac, 0x84,
	0xdf, 0x26, 0x1b, 0x5a, 0x14, 0x69, 0x06, 0x31, 0xe3, 0x3c, 0xce, 0x2c, 0x0b, 0x27, 0x7b, 0x3d,
	0xba, 0x56, 0xc5, 0x1f, 0x71, 0xee, 0xb8, 0xd1, 0x3e, 0x79, 0x7f, 0x86, 0x54, 0xc0, 0xcb, 0xc4,
	0xcc, 0xc0, 0xbe, 0x03, 0xbf, 0x57, 0xa5, 0x22, 0x97, 0xa9, 0xf0, 0x37, 0x49, 0x87, 0x33, 0x91,
	0x4d, 0x5d, 0xe3, 0x04, 0xcb, 0xc2, 0xb8, 0x95, 0xd4, 0xa3, 0x77, 0x5d, 0xf8, 0x11, 0xe7, 0x7b,
	0x36, 0x68, 0x8d, 0x52, 0xe1, 0x78, 0xd5, 0xb6, 0x82, 0xb6, 0x1c, 0x74, 0xc3, 0x65, 0xbe, 0x70,
	0x09, 0x87, 0x0e, 0xbe, 0x3b, 0x5d, 0xe5, 0x4b, 0x5c, 0xe4, 0x98, 0x7c, 0xf4, 0x04, 0xcc, 0x5e,
	0xa9, 0x0d, 0xe6, 0xfb, 0x8c, 0xc3, 0x13, 0x44, 0xae, 0x9f, 0x1b, 0x66, 0x4a, 0x6d, 0xb7, 0x79,
	0x22, 0xb0, 0xb7, 0x22, 0x30, 0x14, 0x27, 0xc2, 0x37, 0xed, 0x71, 0xc8, 0x2d, 0x01, 0x54, 0x1c,
	0xd4, 0xc9, 0x3d, 0x2d, 0x77, 0x1e, 0xf2, 0xe0, 0xad, 0x77, 0xd6, 0x55, 0x97, 0x37, 0x92, 0xf5,
	0x8d, 0x2e, 0x2b, 0xe3, 0x24, 0xc8, 0xc1, 0x2d, 0xd8, 0x8f, 0xda, 0xb3, 0xd8, 0x1e, 0x72, 0x08,
	0xbe, 0x21, 0xd7, 0x9e, 0x02, 0x9b, 0xc0, 0x3e, 0xe4, 0xa3, 0xca, 0xb6, 0xeb, 0x07, 0xd5, 0x63,
	0x3c, 0x76, 0x58, 0x3d, 0x6a, 0xda, 0xe3, 0xa2, 0x02, 0xf5, 0x79, 0x05, 0x82, 0x6f, 0x97, 0x5a,
	0xeb, 0x4b, 0xd4, 0xf0, 0xee, 0x3f, 0x0d, 0xd2, 0xfe, 0x32, 0xc1, 0xfc, 0x39, 0xa8, 0x89, 0x48,
	0x80, 0xfe, 0xe2, 0x91, 0xab, 0xf3, 0x6f, 0x9c, 0x6e, 0x9e, 0xf7, 0xdd, 0xeb, 0x9d, 0x87, 0xd0,
	0xc1, 0xbd, 0x9f, 0xff, 0x3a, 0xfc, 0xad, 0xb6, 0x1b, 0x6c, 0x55, 0x5f, 0x5f, 0x29, 0x75, 0x28,
	0x0a, 0x5e, 0x6a, 0xa3, 0xa6, 0xee, 0x9b, 0x1d, 0xaa, 0x59, 0x41, 0x2c, 0x8a, 0x57, 0x38, 0x70,
	0xaf, 0x96, 0xfe, 0xee, 0x11, 0xba, 0x6a, 0x55, 0x7a, 0xf3, 0x62, 0xef, 0xbf, 0x77, 0x31, 0x9c,
	0x0e, 0x06, 0x8e, 0xdb, 0xfd, 0x60, 0x67, 0x1d, 0x37, 0x69, 0xcb, 0x42, 0xf7, 0x58, 0x8f, 0x79,
	0xce, 0x28, 0xfe, 0xe9, 0x91, 0xee, 0x3a, 0x03, 0xd2, 0x9d, 0x15, 0x02, 0x67, 0x3c, 0x8b, 0xde,
	0x7f, 0x41, 0xeb, 0xe0, 0xa1, 0x23, 0xfd, 0x20, 0xb8, 0xbf, 0x8e, 0x74, 0x0a, 0x26, 0x4e, 0x5c,
	0x75, 0x9c, 0x33, 0x0e, 0x71, 0x6a, 0xeb, 0x63, 0xed, 0x1a, 0x0c, 0xbc, 0x5b, 0xf4, 0x57, 0x8f,
	0xb4, 0xe7, 0x4c, 0x45, 0x3f, 0x59, 0xb9, 0x7e, 0xd1, 0xcd, 0xbd, 0x73, 0x00, 0x3a, 0xf8, 0xdc,
	0x51, 0xba, 0xb3, 0x5e, 0xc7, 0xc9, 0x9d, 0xd0, 0x3a, 0x3d, 0xcc, 0x6c, 0x5d, 0x9c, 0xbb, 0xc2,
	0x81, 0x77, 0xeb, 0xf1, 0x67, 0x2f, 0xb7, 0x52, 0x61, 0xc6, 0xe5, 0xc8, 0x76, 0x0d, 0x39, 0x4c,
	0x76, 0xad, 0x6b, 0x6d, 0x93, 0xc5, 0xbf, 0xfb, 0xa8, 0xe9, 0x7e, 0xd5, 0xf7, 0xfe, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0x71, 0x3b, 0x97, 0xa2, 0xf6, 0x07, 0x00, 0x00,
}
