// Code generated by protoc-gen-go_api(github.com/dev-openapi/protoc-gen-go_api version=v1.0.2). DO NOT EDIT.
// source: douyin-miniapp/oauth.proto

package douyin_miniapp

import (
	context "context"
	fmt "fmt"
	io "io"
	json "encoding/json"
	bytes "bytes"
	http "net/http"
	strings "strings"
)
// Reference imports to suppress errors if they are not otherwise used.
var _ = context.Background
var _ = http.NewRequest
var _ = io.Copy
var _ = bytes.Compare
var _ = json.Marshal
var _ = strings.Compare
var _ = fmt.Errorf


// Client API for Oauth service

type OauthService interface {
	// GetClientToken  生成client_token https://developer.open-douyin.com/docs/resource/zh-CN/dop/develop/openapi/account-permission/client-token
	GetClientToken(ctx context.Context, in *GetClientTokenReq, opts ...Option) (*GetClientTokenRes, error)
}

type oauthService struct {
	// opts
	opts *Options
}

func NewOauthService(opts ...Option) OauthService {
	opt := newOptions(opts...)
	if len(opt.addr) <= 0 {
		opt.addr = "https://open.douyin.com"
	}
	return &oauthService {
		opts: opt,
	}
}


func (c *oauthService) GetClientToken(ctx context.Context, in *GetClientTokenReq, opts ...Option) (*GetClientTokenRes, error) {
	var res GetClientTokenRes
	// options
	opt := buildOptions(c.opts, opts...)
	headers := make(map[string]string)
	// route
	rawURL := fmt.Sprintf("%s/oauth/client_token", opt.addr)

	// body
	var body io.Reader
	bodyForms := make(map[string]string)
	if in.GetClientKey() != "" {
		bodyForms["client_key"] = fmt.Sprintf("%v", in.GetClientKey())
	}
	if in.GetClientSecret() != "" {
		bodyForms["client_secret"] = fmt.Sprintf("%v", in.GetClientSecret())
	}
	if in.GetGrantType() != "" {
		bodyForms["grant_type"] = fmt.Sprintf("%v", in.GetGrantType())
	}
	var bs []string
	for k, v := range bodyForms {
		bs = append(bs, fmt.Sprintf("%s=%s", k, v))
	}
	body = strings.NewReader(strings.Join(bs, "&"))
	headers["Content-Type"] = "multipart/form-data"

	req, err := http.NewRequest("POST", rawURL, body)
	if err != nil {
		return nil, err
	}
	
	// header
	for k, v := range headers {
		req.Header.Set(k, v)
	}
	resp, err := opt.DoRequest(ctx, opt.client, req)
	if err != nil {
		return nil, err
	}
	err = opt.DoResponse(ctx, resp, &res)
	return &res, err 

}
