// Code generated by protoc-gen-go. DO NOT EDIT.
// source: douyin-miniapp/search.proto

package douyin_miniapp // import "github.com/dev-openapi/douyin-miniapp"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateMaSubServiceReq struct {
	SubServiceName       string   `protobuf:"bytes,1,opt,name=sub_service_name,json=subServiceName" json:"sub_service_name,omitempty"`
	SearchKeyWord        []string `protobuf:"bytes,2,rep,name=search_key_word,json=searchKeyWord" json:"search_key_word,omitempty"`
	StartPageUrl         string   `protobuf:"bytes,3,opt,name=start_page_url,json=startPageUrl" json:"start_page_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMaSubServiceReq) Reset()         { *m = CreateMaSubServiceReq{} }
func (m *CreateMaSubServiceReq) String() string { return proto.CompactTextString(m) }
func (*CreateMaSubServiceReq) ProtoMessage()    {}
func (*CreateMaSubServiceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_924ffc9716bb7d78, []int{0}
}
func (m *CreateMaSubServiceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMaSubServiceReq.Unmarshal(m, b)
}
func (m *CreateMaSubServiceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMaSubServiceReq.Marshal(b, m, deterministic)
}
func (dst *CreateMaSubServiceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMaSubServiceReq.Merge(dst, src)
}
func (m *CreateMaSubServiceReq) XXX_Size() int {
	return xxx_messageInfo_CreateMaSubServiceReq.Size(m)
}
func (m *CreateMaSubServiceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMaSubServiceReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMaSubServiceReq proto.InternalMessageInfo

func (m *CreateMaSubServiceReq) GetSubServiceName() string {
	if m != nil {
		return m.SubServiceName
	}
	return ""
}

func (m *CreateMaSubServiceReq) GetSearchKeyWord() []string {
	if m != nil {
		return m.SearchKeyWord
	}
	return nil
}

func (m *CreateMaSubServiceReq) GetStartPageUrl() string {
	if m != nil {
		return m.StartPageUrl
	}
	return ""
}

type CreateMaSubServiceData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMaSubServiceData) Reset()         { *m = CreateMaSubServiceData{} }
func (m *CreateMaSubServiceData) String() string { return proto.CompactTextString(m) }
func (*CreateMaSubServiceData) ProtoMessage()    {}
func (*CreateMaSubServiceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_924ffc9716bb7d78, []int{1}
}
func (m *CreateMaSubServiceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMaSubServiceData.Unmarshal(m, b)
}
func (m *CreateMaSubServiceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMaSubServiceData.Marshal(b, m, deterministic)
}
func (dst *CreateMaSubServiceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMaSubServiceData.Merge(dst, src)
}
func (m *CreateMaSubServiceData) XXX_Size() int {
	return xxx_messageInfo_CreateMaSubServiceData.Size(m)
}
func (m *CreateMaSubServiceData) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMaSubServiceData.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMaSubServiceData proto.InternalMessageInfo

type CreateMaSubServiceRes struct {
	ErrNo                int32                   `protobuf:"varint,1,opt,name=err_no,json=errNo" json:"err_no,omitempty"`
	ErrMsg               string                  `protobuf:"bytes,2,opt,name=err_msg,json=errMsg" json:"err_msg,omitempty"`
	LogId                string                  `protobuf:"bytes,3,opt,name=log_id,json=logId" json:"log_id,omitempty"`
	Data                 *CreateMaSubServiceData `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CreateMaSubServiceRes) Reset()         { *m = CreateMaSubServiceRes{} }
func (m *CreateMaSubServiceRes) String() string { return proto.CompactTextString(m) }
func (*CreateMaSubServiceRes) ProtoMessage()    {}
func (*CreateMaSubServiceRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_924ffc9716bb7d78, []int{2}
}
func (m *CreateMaSubServiceRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMaSubServiceRes.Unmarshal(m, b)
}
func (m *CreateMaSubServiceRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMaSubServiceRes.Marshal(b, m, deterministic)
}
func (dst *CreateMaSubServiceRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMaSubServiceRes.Merge(dst, src)
}
func (m *CreateMaSubServiceRes) XXX_Size() int {
	return xxx_messageInfo_CreateMaSubServiceRes.Size(m)
}
func (m *CreateMaSubServiceRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMaSubServiceRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMaSubServiceRes proto.InternalMessageInfo

func (m *CreateMaSubServiceRes) GetErrNo() int32 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *CreateMaSubServiceRes) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CreateMaSubServiceRes) GetLogId() string {
	if m != nil {
		return m.LogId
	}
	return ""
}

func (m *CreateMaSubServiceRes) GetData() *CreateMaSubServiceData {
	if m != nil {
		return m.Data
	}
	return nil
}

type QueryMaSubServiceReq struct {
	ApprovalState        int64    `protobuf:"varint,1,opt,name=approval_state,json=approvalState" json:"approval_state,omitempty"`
	PageNo               int64    `protobuf:"varint,2,opt,name=page_no,json=pageNo" json:"page_no,omitempty"`
	PageSize             int64    `protobuf:"varint,3,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryMaSubServiceReq) Reset()         { *m = QueryMaSubServiceReq{} }
func (m *QueryMaSubServiceReq) String() string { return proto.CompactTextString(m) }
func (*QueryMaSubServiceReq) ProtoMessage()    {}
func (*QueryMaSubServiceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_924ffc9716bb7d78, []int{3}
}
func (m *QueryMaSubServiceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryMaSubServiceReq.Unmarshal(m, b)
}
func (m *QueryMaSubServiceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryMaSubServiceReq.Marshal(b, m, deterministic)
}
func (dst *QueryMaSubServiceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMaSubServiceReq.Merge(dst, src)
}
func (m *QueryMaSubServiceReq) XXX_Size() int {
	return xxx_messageInfo_QueryMaSubServiceReq.Size(m)
}
func (m *QueryMaSubServiceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMaSubServiceReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMaSubServiceReq proto.InternalMessageInfo

func (m *QueryMaSubServiceReq) GetApprovalState() int64 {
	if m != nil {
		return m.ApprovalState
	}
	return 0
}

func (m *QueryMaSubServiceReq) GetPageNo() int64 {
	if m != nil {
		return m.PageNo
	}
	return 0
}

func (m *QueryMaSubServiceReq) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ApprovalReason struct {
	Reason               string   `protobuf:"bytes,1,opt,name=reason" json:"reason,omitempty"`
	AuditField           string   `protobuf:"bytes,2,opt,name=audit_field,json=auditField" json:"audit_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApprovalReason) Reset()         { *m = ApprovalReason{} }
func (m *ApprovalReason) String() string { return proto.CompactTextString(m) }
func (*ApprovalReason) ProtoMessage()    {}
func (*ApprovalReason) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_924ffc9716bb7d78, []int{4}
}
func (m *ApprovalReason) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApprovalReason.Unmarshal(m, b)
}
func (m *ApprovalReason) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApprovalReason.Marshal(b, m, deterministic)
}
func (dst *ApprovalReason) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApprovalReason.Merge(dst, src)
}
func (m *ApprovalReason) XXX_Size() int {
	return xxx_messageInfo_ApprovalReason.Size(m)
}
func (m *ApprovalReason) XXX_DiscardUnknown() {
	xxx_messageInfo_ApprovalReason.DiscardUnknown(m)
}

var xxx_messageInfo_ApprovalReason proto.InternalMessageInfo

func (m *ApprovalReason) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *ApprovalReason) GetAuditField() string {
	if m != nil {
		return m.AuditField
	}
	return ""
}

type MaSubServiceInfo struct {
	MicroAppId           string            `protobuf:"bytes,1,opt,name=micro_app_id,json=microAppId" json:"micro_app_id,omitempty"`
	SubServiceId         string            `protobuf:"bytes,2,opt,name=sub_service_id,json=subServiceId" json:"sub_service_id,omitempty"`
	SubServiceName       string            `protobuf:"bytes,3,opt,name=sub_service_name,json=subServiceName" json:"sub_service_name,omitempty"`
	MicroAppIcon         string            `protobuf:"bytes,4,opt,name=micro_app_icon,json=microAppIcon" json:"micro_app_icon,omitempty"`
	SearchKeyWord        []string          `protobuf:"bytes,5,rep,name=search_key_word,json=searchKeyWord" json:"search_key_word,omitempty"`
	StartPageUrl         string            `protobuf:"bytes,6,opt,name=start_page_url,json=startPageUrl" json:"start_page_url,omitempty"`
	ApprovalState        int32             `protobuf:"varint,7,opt,name=approval_state,json=approvalState" json:"approval_state,omitempty"`
	CreateTime           string            `protobuf:"bytes,8,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	Reasons              []*ApprovalReason `protobuf:"bytes,9,rep,name=reasons" json:"reasons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MaSubServiceInfo) Reset()         { *m = MaSubServiceInfo{} }
func (m *MaSubServiceInfo) String() string { return proto.CompactTextString(m) }
func (*MaSubServiceInfo) ProtoMessage()    {}
func (*MaSubServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_924ffc9716bb7d78, []int{5}
}
func (m *MaSubServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaSubServiceInfo.Unmarshal(m, b)
}
func (m *MaSubServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaSubServiceInfo.Marshal(b, m, deterministic)
}
func (dst *MaSubServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaSubServiceInfo.Merge(dst, src)
}
func (m *MaSubServiceInfo) XXX_Size() int {
	return xxx_messageInfo_MaSubServiceInfo.Size(m)
}
func (m *MaSubServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MaSubServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MaSubServiceInfo proto.InternalMessageInfo

func (m *MaSubServiceInfo) GetMicroAppId() string {
	if m != nil {
		return m.MicroAppId
	}
	return ""
}

func (m *MaSubServiceInfo) GetSubServiceId() string {
	if m != nil {
		return m.SubServiceId
	}
	return ""
}

func (m *MaSubServiceInfo) GetSubServiceName() string {
	if m != nil {
		return m.SubServiceName
	}
	return ""
}

func (m *MaSubServiceInfo) GetMicroAppIcon() string {
	if m != nil {
		return m.MicroAppIcon
	}
	return ""
}

func (m *MaSubServiceInfo) GetSearchKeyWord() []string {
	if m != nil {
		return m.SearchKeyWord
	}
	return nil
}

func (m *MaSubServiceInfo) GetStartPageUrl() string {
	if m != nil {
		return m.StartPageUrl
	}
	return ""
}

func (m *MaSubServiceInfo) GetApprovalState() int32 {
	if m != nil {
		return m.ApprovalState
	}
	return 0
}

func (m *MaSubServiceInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *MaSubServiceInfo) GetReasons() []*ApprovalReason {
	if m != nil {
		return m.Reasons
	}
	return nil
}

type QueryMaSubServiceData struct {
	HasMore              bool                `protobuf:"varint,1,opt,name=has_more,json=hasMore" json:"has_more,omitempty"`
	Total                int64               `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
	MaSubServiceInfoList []*MaSubServiceInfo `protobuf:"bytes,3,rep,name=ma_sub_service_info_list,json=maSubServiceInfoList" json:"ma_sub_service_info_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueryMaSubServiceData) Reset()         { *m = QueryMaSubServiceData{} }
func (m *QueryMaSubServiceData) String() string { return proto.CompactTextString(m) }
func (*QueryMaSubServiceData) ProtoMessage()    {}
func (*QueryMaSubServiceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_924ffc9716bb7d78, []int{6}
}
func (m *QueryMaSubServiceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryMaSubServiceData.Unmarshal(m, b)
}
func (m *QueryMaSubServiceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryMaSubServiceData.Marshal(b, m, deterministic)
}
func (dst *QueryMaSubServiceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMaSubServiceData.Merge(dst, src)
}
func (m *QueryMaSubServiceData) XXX_Size() int {
	return xxx_messageInfo_QueryMaSubServiceData.Size(m)
}
func (m *QueryMaSubServiceData) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMaSubServiceData.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMaSubServiceData proto.InternalMessageInfo

func (m *QueryMaSubServiceData) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

func (m *QueryMaSubServiceData) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *QueryMaSubServiceData) GetMaSubServiceInfoList() []*MaSubServiceInfo {
	if m != nil {
		return m.MaSubServiceInfoList
	}
	return nil
}

type QueryMaSubServiceRes struct {
	ErrNo                int32                  `protobuf:"varint,1,opt,name=err_no,json=errNo" json:"err_no,omitempty"`
	ErrMsg               string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg" json:"err_msg,omitempty"`
	LogId                string                 `protobuf:"bytes,3,opt,name=log_id,json=logId" json:"log_id,omitempty"`
	Data                 *QueryMaSubServiceData `protobuf:"bytes,10,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *QueryMaSubServiceRes) Reset()         { *m = QueryMaSubServiceRes{} }
func (m *QueryMaSubServiceRes) String() string { return proto.CompactTextString(m) }
func (*QueryMaSubServiceRes) ProtoMessage()    {}
func (*QueryMaSubServiceRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_924ffc9716bb7d78, []int{7}
}
func (m *QueryMaSubServiceRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryMaSubServiceRes.Unmarshal(m, b)
}
func (m *QueryMaSubServiceRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryMaSubServiceRes.Marshal(b, m, deterministic)
}
func (dst *QueryMaSubServiceRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMaSubServiceRes.Merge(dst, src)
}
func (m *QueryMaSubServiceRes) XXX_Size() int {
	return xxx_messageInfo_QueryMaSubServiceRes.Size(m)
}
func (m *QueryMaSubServiceRes) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMaSubServiceRes.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMaSubServiceRes proto.InternalMessageInfo

func (m *QueryMaSubServiceRes) GetErrNo() int32 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *QueryMaSubServiceRes) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *QueryMaSubServiceRes) GetLogId() string {
	if m != nil {
		return m.LogId
	}
	return ""
}

func (m *QueryMaSubServiceRes) GetData() *QueryMaSubServiceData {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteMaSubServiceReq struct {
	SubServiceId         string   `protobuf:"bytes,1,opt,name=sub_service_id,json=subServiceId" json:"sub_service_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMaSubServiceReq) Reset()         { *m = DeleteMaSubServiceReq{} }
func (m *DeleteMaSubServiceReq) String() string { return proto.CompactTextString(m) }
func (*DeleteMaSubServiceReq) ProtoMessage()    {}
func (*DeleteMaSubServiceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_924ffc9716bb7d78, []int{8}
}
func (m *DeleteMaSubServiceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMaSubServiceReq.Unmarshal(m, b)
}
func (m *DeleteMaSubServiceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMaSubServiceReq.Marshal(b, m, deterministic)
}
func (dst *DeleteMaSubServiceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMaSubServiceReq.Merge(dst, src)
}
func (m *DeleteMaSubServiceReq) XXX_Size() int {
	return xxx_messageInfo_DeleteMaSubServiceReq.Size(m)
}
func (m *DeleteMaSubServiceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMaSubServiceReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMaSubServiceReq proto.InternalMessageInfo

func (m *DeleteMaSubServiceReq) GetSubServiceId() string {
	if m != nil {
		return m.SubServiceId
	}
	return ""
}

type DeleteMaSubServiceData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMaSubServiceData) Reset()         { *m = DeleteMaSubServiceData{} }
func (m *DeleteMaSubServiceData) String() string { return proto.CompactTextString(m) }
func (*DeleteMaSubServiceData) ProtoMessage()    {}
func (*DeleteMaSubServiceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_924ffc9716bb7d78, []int{9}
}
func (m *DeleteMaSubServiceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMaSubServiceData.Unmarshal(m, b)
}
func (m *DeleteMaSubServiceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMaSubServiceData.Marshal(b, m, deterministic)
}
func (dst *DeleteMaSubServiceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMaSubServiceData.Merge(dst, src)
}
func (m *DeleteMaSubServiceData) XXX_Size() int {
	return xxx_messageInfo_DeleteMaSubServiceData.Size(m)
}
func (m *DeleteMaSubServiceData) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMaSubServiceData.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMaSubServiceData proto.InternalMessageInfo

type DeleteMaSubServiceRes struct {
	ErrNo                int32                   `protobuf:"varint,1,opt,name=err_no,json=errNo" json:"err_no,omitempty"`
	ErrMsg               string                  `protobuf:"bytes,2,opt,name=err_msg,json=errMsg" json:"err_msg,omitempty"`
	LogId                string                  `protobuf:"bytes,3,opt,name=log_id,json=logId" json:"log_id,omitempty"`
	Data                 *DeleteMaSubServiceData `protobuf:"bytes,10,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *DeleteMaSubServiceRes) Reset()         { *m = DeleteMaSubServiceRes{} }
func (m *DeleteMaSubServiceRes) String() string { return proto.CompactTextString(m) }
func (*DeleteMaSubServiceRes) ProtoMessage()    {}
func (*DeleteMaSubServiceRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_924ffc9716bb7d78, []int{10}
}
func (m *DeleteMaSubServiceRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMaSubServiceRes.Unmarshal(m, b)
}
func (m *DeleteMaSubServiceRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMaSubServiceRes.Marshal(b, m, deterministic)
}
func (dst *DeleteMaSubServiceRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMaSubServiceRes.Merge(dst, src)
}
func (m *DeleteMaSubServiceRes) XXX_Size() int {
	return xxx_messageInfo_DeleteMaSubServiceRes.Size(m)
}
func (m *DeleteMaSubServiceRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMaSubServiceRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMaSubServiceRes proto.InternalMessageInfo

func (m *DeleteMaSubServiceRes) GetErrNo() int32 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *DeleteMaSubServiceRes) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *DeleteMaSubServiceRes) GetLogId() string {
	if m != nil {
		return m.LogId
	}
	return ""
}

func (m *DeleteMaSubServiceRes) GetData() *DeleteMaSubServiceData {
	if m != nil {
		return m.Data
	}
	return nil
}

type CheckMaSubServiceReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckMaSubServiceReq) Reset()         { *m = CheckMaSubServiceReq{} }
func (m *CheckMaSubServiceReq) String() string { return proto.CompactTextString(m) }
func (*CheckMaSubServiceReq) ProtoMessage()    {}
func (*CheckMaSubServiceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_924ffc9716bb7d78, []int{11}
}
func (m *CheckMaSubServiceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckMaSubServiceReq.Unmarshal(m, b)
}
func (m *CheckMaSubServiceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckMaSubServiceReq.Marshal(b, m, deterministic)
}
func (dst *CheckMaSubServiceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckMaSubServiceReq.Merge(dst, src)
}
func (m *CheckMaSubServiceReq) XXX_Size() int {
	return xxx_messageInfo_CheckMaSubServiceReq.Size(m)
}
func (m *CheckMaSubServiceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckMaSubServiceReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckMaSubServiceReq proto.InternalMessageInfo

type CheckMaSubServiceData struct {
	HasPermission        bool     `protobuf:"varint,1,opt,name=has_permission,json=hasPermission" json:"has_permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckMaSubServiceData) Reset()         { *m = CheckMaSubServiceData{} }
func (m *CheckMaSubServiceData) String() string { return proto.CompactTextString(m) }
func (*CheckMaSubServiceData) ProtoMessage()    {}
func (*CheckMaSubServiceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_924ffc9716bb7d78, []int{12}
}
func (m *CheckMaSubServiceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckMaSubServiceData.Unmarshal(m, b)
}
func (m *CheckMaSubServiceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckMaSubServiceData.Marshal(b, m, deterministic)
}
func (dst *CheckMaSubServiceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckMaSubServiceData.Merge(dst, src)
}
func (m *CheckMaSubServiceData) XXX_Size() int {
	return xxx_messageInfo_CheckMaSubServiceData.Size(m)
}
func (m *CheckMaSubServiceData) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckMaSubServiceData.DiscardUnknown(m)
}

var xxx_messageInfo_CheckMaSubServiceData proto.InternalMessageInfo

func (m *CheckMaSubServiceData) GetHasPermission() bool {
	if m != nil {
		return m.HasPermission
	}
	return false
}

type CheckMaSubServiceRes struct {
	ErrNo                int32                  `protobuf:"varint,1,opt,name=err_no,json=errNo" json:"err_no,omitempty"`
	ErrMsg               string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg" json:"err_msg,omitempty"`
	LogId                string                 `protobuf:"bytes,3,opt,name=log_id,json=logId" json:"log_id,omitempty"`
	Data                 *CheckMaSubServiceData `protobuf:"bytes,10,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CheckMaSubServiceRes) Reset()         { *m = CheckMaSubServiceRes{} }
func (m *CheckMaSubServiceRes) String() string { return proto.CompactTextString(m) }
func (*CheckMaSubServiceRes) ProtoMessage()    {}
func (*CheckMaSubServiceRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_924ffc9716bb7d78, []int{13}
}
func (m *CheckMaSubServiceRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckMaSubServiceRes.Unmarshal(m, b)
}
func (m *CheckMaSubServiceRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckMaSubServiceRes.Marshal(b, m, deterministic)
}
func (dst *CheckMaSubServiceRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckMaSubServiceRes.Merge(dst, src)
}
func (m *CheckMaSubServiceRes) XXX_Size() int {
	return xxx_messageInfo_CheckMaSubServiceRes.Size(m)
}
func (m *CheckMaSubServiceRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckMaSubServiceRes.DiscardUnknown(m)
}

var xxx_messageInfo_CheckMaSubServiceRes proto.InternalMessageInfo

func (m *CheckMaSubServiceRes) GetErrNo() int32 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *CheckMaSubServiceRes) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CheckMaSubServiceRes) GetLogId() string {
	if m != nil {
		return m.LogId
	}
	return ""
}

func (m *CheckMaSubServiceRes) GetData() *CheckMaSubServiceData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateMaSubServiceReq)(nil), "developer.toutiao.com.CreateMaSubServiceReq")
	proto.RegisterType((*CreateMaSubServiceData)(nil), "developer.toutiao.com.CreateMaSubServiceData")
	proto.RegisterType((*CreateMaSubServiceRes)(nil), "developer.toutiao.com.CreateMaSubServiceRes")
	proto.RegisterType((*QueryMaSubServiceReq)(nil), "developer.toutiao.com.QueryMaSubServiceReq")
	proto.RegisterType((*ApprovalReason)(nil), "developer.toutiao.com.ApprovalReason")
	proto.RegisterType((*MaSubServiceInfo)(nil), "developer.toutiao.com.MaSubServiceInfo")
	proto.RegisterType((*QueryMaSubServiceData)(nil), "developer.toutiao.com.QueryMaSubServiceData")
	proto.RegisterType((*QueryMaSubServiceRes)(nil), "developer.toutiao.com.QueryMaSubServiceRes")
	proto.RegisterType((*DeleteMaSubServiceReq)(nil), "developer.toutiao.com.DeleteMaSubServiceReq")
	proto.RegisterType((*DeleteMaSubServiceData)(nil), "developer.toutiao.com.DeleteMaSubServiceData")
	proto.RegisterType((*DeleteMaSubServiceRes)(nil), "developer.toutiao.com.DeleteMaSubServiceRes")
	proto.RegisterType((*CheckMaSubServiceReq)(nil), "developer.toutiao.com.CheckMaSubServiceReq")
	proto.RegisterType((*CheckMaSubServiceData)(nil), "developer.toutiao.com.CheckMaSubServiceData")
	proto.RegisterType((*CheckMaSubServiceRes)(nil), "developer.toutiao.com.CheckMaSubServiceRes")
}

func init() {
	proto.RegisterFile("douyin-miniapp/search.proto", fileDescriptor_search_924ffc9716bb7d78)
}

var fileDescriptor_search_924ffc9716bb7d78 = []byte{
	// 879 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x96, 0xeb, 0x4d, 0x9a, 0x9c, 0xb6, 0x61, 0x19, 0x35, 0xc5, 0x74, 0x91, 0x36, 0xb2, 0xb6,
	0x6c, 0xd4, 0x6d, 0x13, 0xe8, 0x4a, 0x5c, 0x20, 0xf1, 0x53, 0x76, 0x85, 0x14, 0x41, 0xab, 0xc5,
	0x01, 0x21, 0x71, 0x63, 0x4d, 0xed, 0x53, 0x67, 0xb4, 0xb6, 0x67, 0x3a, 0x33, 0x09, 0xca, 0xde,
	0xc1, 0x0b, 0x70, 0xc1, 0x03, 0xa0, 0xbd, 0x40, 0x02, 0x5e, 0x87, 0x57, 0xe0, 0x41, 0xd0, 0x8c,
	0xdd, 0xd2, 0xc6, 0x0e, 0x34, 0x52, 0xc5, 0x5d, 0xfc, 0xf9, 0x9c, 0x33, 0xdf, 0x7c, 0xe7, 0x3b,
	0x27, 0x86, 0x07, 0x31, 0x9f, 0xce, 0x59, 0x7e, 0x98, 0xb1, 0x9c, 0x51, 0x21, 0x86, 0x0a, 0xa9,
	0x8c, 0x26, 0x03, 0x21, 0xb9, 0xe6, 0xa4, 0x1b, 0xe3, 0x0c, 0x53, 0x2e, 0x50, 0x0e, 0x34, 0x9f,
	0x6a, 0x46, 0xf9, 0x20, 0xe2, 0xd9, 0xee, 0x3b, 0x09, 0xe7, 0x49, 0x8a, 0x43, 0x2a, 0xd8, 0x90,
	0xe6, 0x39, 0xd7, 0x54, 0x33, 0x9e, 0xab, 0x22, 0xc9, 0xff, 0xc9, 0x81, 0xee, 0x33, 0x89, 0x54,
	0xe3, 0x09, 0x1d, 0x4f, 0xcf, 0xc6, 0x28, 0x67, 0x2c, 0xc2, 0x00, 0x2f, 0x48, 0x1f, 0xee, 0xab,
	0xe9, 0x59, 0xa8, 0x0a, 0x24, 0xcc, 0x69, 0x86, 0x9e, 0xd3, 0x73, 0xfa, 0xed, 0xa0, 0xa3, 0xae,
	0x02, 0x4f, 0x69, 0x86, 0xe4, 0x5d, 0x78, 0xa3, 0x20, 0x12, 0xbe, 0xc4, 0x79, 0xf8, 0x3d, 0x97,
	0xb1, 0xb7, 0xd6, 0x73, 0xfb, 0xed, 0x60, 0xab, 0x80, 0xbf, 0xc0, 0xf9, 0xb7, 0x5c, 0xc6, 0xe4,
	0x11, 0x74, 0x94, 0xa6, 0x52, 0x87, 0x82, 0x26, 0x18, 0x4e, 0x65, 0xea, 0xb9, 0xb6, 0xde, 0xa6,
	0x45, 0x5f, 0xd0, 0x04, 0xbf, 0x91, 0xa9, 0xef, 0xc1, 0x4e, 0x95, 0xd0, 0x73, 0xaa, 0xa9, 0xff,
	0x7a, 0x09, 0x57, 0x45, 0xba, 0xd0, 0x44, 0x29, 0xc3, 0x9c, 0x5b, 0x86, 0x8d, 0xa0, 0x81, 0x52,
	0x9e, 0x72, 0xf2, 0x16, 0xac, 0x1b, 0x38, 0x53, 0x89, 0xb7, 0x66, 0x4f, 0x32, 0x51, 0x27, 0x2a,
	0x31, 0xf1, 0x29, 0x4f, 0x42, 0x16, 0x97, 0x0c, 0x1a, 0x29, 0x4f, 0x46, 0x31, 0x39, 0x86, 0x7b,
	0x31, 0xd5, 0xd4, 0xbb, 0xd7, 0x73, 0xfa, 0x1b, 0x47, 0x87, 0x83, 0x5a, 0x41, 0x07, 0xf5, 0xec,
	0x02, 0x9b, 0xea, 0x2b, 0xd8, 0xfe, 0x6a, 0x8a, 0x72, 0xbe, 0xa8, 0xe6, 0x1e, 0x74, 0xa8, 0x10,
	0x92, 0xcf, 0x68, 0x1a, 0x2a, 0x4d, 0x75, 0xa1, 0xa5, 0x1b, 0x6c, 0x5d, 0xa2, 0x63, 0x03, 0x1a,
	0xc6, 0x56, 0x9c, 0x9c, 0x5b, 0xc6, 0x6e, 0xd0, 0x34, 0x8f, 0xa7, 0x9c, 0x3c, 0x80, 0xb6, 0x7d,
	0xa1, 0xd8, 0x2b, 0xb4, 0xa4, 0xdd, 0xa0, 0x65, 0x80, 0x31, 0x7b, 0x85, 0xfe, 0x08, 0x3a, 0xc7,
	0x65, 0x99, 0x00, 0xa9, 0xe2, 0x39, 0xd9, 0x81, 0xa6, 0xb4, 0xbf, 0xca, 0x96, 0x95, 0x4f, 0xe4,
	0x21, 0x6c, 0xd0, 0x69, 0xcc, 0x74, 0x78, 0xce, 0x30, 0x8d, 0x4b, 0x55, 0xc0, 0x42, 0x9f, 0x1b,
	0xc4, 0xff, 0xc1, 0x85, 0xfb, 0xd7, 0xb9, 0x8f, 0xf2, 0x73, 0x4e, 0x7a, 0xb0, 0x99, 0xb1, 0x48,
	0xf2, 0x90, 0x0a, 0x61, 0x44, 0x2b, 0x6a, 0x82, 0xc5, 0x8e, 0x85, 0x18, 0x15, 0xad, 0xbd, 0x66,
	0x16, 0x76, 0x59, 0x7a, 0xf3, 0x1f, 0xab, 0x8c, 0xe2, 0x5a, 0x4b, 0xb9, 0xb5, 0x96, 0x7a, 0x04,
	0x9d, 0x6b, 0x27, 0x46, 0x3c, 0xb7, 0x3d, 0x69, 0x07, 0x9b, 0x57, 0x67, 0x46, 0x3c, 0xaf, 0x33,
	0x5e, 0xe3, 0x76, 0xc6, 0x6b, 0x56, 0x8d, 0x57, 0xd3, 0xa2, 0x75, 0x6b, 0xa6, 0x85, 0x16, 0x3d,
	0x84, 0x8d, 0xc8, 0x3a, 0x20, 0xd4, 0x2c, 0x43, 0xaf, 0x55, 0x68, 0x51, 0x40, 0x5f, 0xb3, 0x0c,
	0xc9, 0x27, 0xb0, 0x5e, 0xa8, 0xad, 0xbc, 0x76, 0xcf, 0xed, 0x6f, 0x1c, 0xed, 0x2d, 0x31, 0xd2,
	0xcd, 0x9e, 0x05, 0x97, 0x59, 0xfe, 0xef, 0x0e, 0x74, 0x2b, 0x26, 0x32, 0x1e, 0x23, 0x6f, 0x43,
	0x6b, 0x42, 0x55, 0x98, 0x71, 0x59, 0xf8, 0xa7, 0x15, 0xac, 0x4f, 0xa8, 0x3a, 0xe1, 0x12, 0xc9,
	0x36, 0x34, 0x34, 0xd7, 0x34, 0x2d, 0x7d, 0x53, 0x3c, 0x90, 0x10, 0xbc, 0x8c, 0x86, 0x37, 0x5a,
	0x93, 0x9f, 0xf3, 0x30, 0x65, 0x4a, 0x7b, 0xae, 0x25, 0xf7, 0x78, 0x09, 0xb9, 0x45, 0x13, 0x04,
	0xdb, 0xd9, 0x02, 0xf2, 0x25, 0x53, 0xda, 0xff, 0xc5, 0xa9, 0x35, 0xfc, 0x9d, 0x8d, 0xe4, 0xa7,
	0xe5, 0x48, 0x82, 0x1d, 0xc9, 0x83, 0x25, 0x64, 0x6b, 0xd5, 0x2a, 0x27, 0xf2, 0x23, 0xe8, 0x3e,
	0xc7, 0x14, 0xab, 0x0b, 0xae, 0xea, 0x59, 0xa7, 0xea, 0x59, 0xb3, 0x8e, 0xaa, 0xe9, 0x57, 0xeb,
	0xa8, 0xae, 0xf2, 0x9d, 0xaf, 0x23, 0xf8, 0xd7, 0x75, 0x54, 0xcf, 0xae, 0xbc, 0xfc, 0x0e, 0x6c,
	0x3f, 0x9b, 0x60, 0xf4, 0x72, 0xe1, 0xee, 0xfe, 0xc7, 0xd0, 0xad, 0xe0, 0xd6, 0x61, 0x7b, 0xd0,
	0x31, 0x0e, 0x13, 0x28, 0x33, 0xa6, 0x14, 0x2b, 0x17, 0x48, 0x2b, 0xd8, 0x9a, 0x50, 0xf5, 0xe2,
	0x0a, 0xb4, 0x6d, 0xaf, 0x29, 0xfc, 0x3f, 0xb7, 0xbd, 0xf6, 0x0a, 0xc5, 0xcd, 0x8f, 0xfe, 0x68,
	0xc0, 0xd6, 0xd8, 0x6e, 0x81, 0xf2, 0x1d, 0xf9, 0xcd, 0x01, 0x52, 0xdd, 0xdd, 0xe4, 0xe0, 0xd6,
	0x6b, 0x3e, 0xc0, 0x8b, 0xdd, 0x55, 0xa2, 0x95, 0xff, 0xc1, 0x8f, 0x7f, 0xfe, 0xf5, 0xf3, 0xda,
	0x7b, 0xfe, 0x93, 0xe2, 0xdf, 0x57, 0x08, 0x35, 0x9c, 0xbd, 0x3f, 0x8c, 0xa8, 0xa0, 0x11, 0xd3,
	0xf3, 0x61, 0xb9, 0x47, 0x6e, 0x4e, 0xe8, 0x87, 0xce, 0x3e, 0x79, 0xed, 0xc0, 0x9b, 0x15, 0x4f,
	0x93, 0x27, 0xb7, 0x75, 0xbf, 0x21, 0xba, 0x42, 0xb0, 0xf2, 0x8f, 0x2c, 0xcf, 0x03, 0xb2, 0x5f,
	0xcf, 0xf3, 0xc2, 0xe4, 0x2c, 0xd0, 0x24, 0xbf, 0x3a, 0x40, 0xaa, 0xde, 0x5b, 0x2a, 0x67, 0xed,
	0x0c, 0xee, 0xae, 0x12, 0xad, 0xfc, 0xa7, 0x96, 0xe6, 0xe1, 0xfe, 0x12, 0x39, 0x63, 0x9b, 0xb4,
	0xc8, 0xd3, 0x68, 0x59, 0x31, 0xca, 0x52, 0x2d, 0xeb, 0xa6, 0x65, 0x77, 0x85, 0xe0, 0xff, 0xd4,
	0x32, 0x32, 0x39, 0x0b, 0x1c, 0x3f, 0x7b, 0xfc, 0xdd, 0x5e, 0xc2, 0xf4, 0x64, 0x7a, 0x66, 0xca,
	0x0e, 0x63, 0x9c, 0x1d, 0x72, 0x81, 0xb9, 0xc9, 0xbf, 0xf9, 0xc1, 0x77, 0xd6, 0xb4, 0x5f, 0x6d,
	0x4f, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xcc, 0x11, 0x41, 0x09, 0x0a, 0x00, 0x00,
}
