// Code generated by protoc-gen-go. DO NOT EDIT.
// source: douyin-miniapp/share.proto

package douyin_miniapp // import "github.com/dev-openapi/douyin-miniapp"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GenerateReq struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	MaAppId              string   `protobuf:"bytes,2,opt,name=ma_app_id,json=maAppId" json:"ma_app_id,omitempty"`
	AppName              string   `protobuf:"bytes,3,opt,name=app_name,json=appName" json:"app_name,omitempty"`
	Path                 string   `protobuf:"bytes,4,opt,name=path" json:"path,omitempty"`
	Query                string   `protobuf:"bytes,5,opt,name=query" json:"query,omitempty"`
	ExpireTime           int64    `protobuf:"varint,6,opt,name=expire_time,json=expireTime" json:"expire_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateReq) Reset()         { *m = GenerateReq{} }
func (m *GenerateReq) String() string { return proto.CompactTextString(m) }
func (*GenerateReq) ProtoMessage()    {}
func (*GenerateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_share_ce06d67b2b437624, []int{0}
}
func (m *GenerateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateReq.Unmarshal(m, b)
}
func (m *GenerateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateReq.Marshal(b, m, deterministic)
}
func (dst *GenerateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateReq.Merge(dst, src)
}
func (m *GenerateReq) XXX_Size() int {
	return xxx_messageInfo_GenerateReq.Size(m)
}
func (m *GenerateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateReq.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateReq proto.InternalMessageInfo

func (m *GenerateReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GenerateReq) GetMaAppId() string {
	if m != nil {
		return m.MaAppId
	}
	return ""
}

func (m *GenerateReq) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *GenerateReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GenerateReq) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *GenerateReq) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

type GenerateRes struct {
	ErrNo                int64    `protobuf:"varint,1,opt,name=err_no,json=errNo" json:"err_no,omitempty"`
	ErrTips              string   `protobuf:"bytes,2,opt,name=err_tips,json=errTips" json:"err_tips,omitempty"`
	UrlLink              string   `protobuf:"bytes,3,opt,name=url_link,json=urlLink" json:"url_link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateRes) Reset()         { *m = GenerateRes{} }
func (m *GenerateRes) String() string { return proto.CompactTextString(m) }
func (*GenerateRes) ProtoMessage()    {}
func (*GenerateRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_share_ce06d67b2b437624, []int{1}
}
func (m *GenerateRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateRes.Unmarshal(m, b)
}
func (m *GenerateRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateRes.Marshal(b, m, deterministic)
}
func (dst *GenerateRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateRes.Merge(dst, src)
}
func (m *GenerateRes) XXX_Size() int {
	return xxx_messageInfo_GenerateRes.Size(m)
}
func (m *GenerateRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateRes.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateRes proto.InternalMessageInfo

func (m *GenerateRes) GetErrNo() int64 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *GenerateRes) GetErrTips() string {
	if m != nil {
		return m.ErrTips
	}
	return ""
}

func (m *GenerateRes) GetUrlLink() string {
	if m != nil {
		return m.UrlLink
	}
	return ""
}

type QueryInfoReq struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	UrlLink              string   `protobuf:"bytes,2,opt,name=url_link,json=urlLink" json:"url_link,omitempty"`
	MaAppId              string   `protobuf:"bytes,3,opt,name=ma_app_id,json=maAppId" json:"ma_app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryInfoReq) Reset()         { *m = QueryInfoReq{} }
func (m *QueryInfoReq) String() string { return proto.CompactTextString(m) }
func (*QueryInfoReq) ProtoMessage()    {}
func (*QueryInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_share_ce06d67b2b437624, []int{2}
}
func (m *QueryInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryInfoReq.Unmarshal(m, b)
}
func (m *QueryInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryInfoReq.Marshal(b, m, deterministic)
}
func (dst *QueryInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInfoReq.Merge(dst, src)
}
func (m *QueryInfoReq) XXX_Size() int {
	return xxx_messageInfo_QueryInfoReq.Size(m)
}
func (m *QueryInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInfoReq proto.InternalMessageInfo

func (m *QueryInfoReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *QueryInfoReq) GetUrlLink() string {
	if m != nil {
		return m.UrlLink
	}
	return ""
}

func (m *QueryInfoReq) GetMaAppId() string {
	if m != nil {
		return m.MaAppId
	}
	return ""
}

type URLLinkInfo struct {
	CreateTime           int64    `protobuf:"varint,1,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	MaAppId              string   `protobuf:"bytes,2,opt,name=ma_app_id,json=maAppId" json:"ma_app_id,omitempty"`
	AppName              string   `protobuf:"bytes,3,opt,name=app_name,json=appName" json:"app_name,omitempty"`
	Path                 string   `protobuf:"bytes,4,opt,name=path" json:"path,omitempty"`
	Query                string   `protobuf:"bytes,5,opt,name=query" json:"query,omitempty"`
	ExpireTime           int64    `protobuf:"varint,6,opt,name=expire_time,json=expireTime" json:"expire_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URLLinkInfo) Reset()         { *m = URLLinkInfo{} }
func (m *URLLinkInfo) String() string { return proto.CompactTextString(m) }
func (*URLLinkInfo) ProtoMessage()    {}
func (*URLLinkInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_share_ce06d67b2b437624, []int{3}
}
func (m *URLLinkInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URLLinkInfo.Unmarshal(m, b)
}
func (m *URLLinkInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URLLinkInfo.Marshal(b, m, deterministic)
}
func (dst *URLLinkInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URLLinkInfo.Merge(dst, src)
}
func (m *URLLinkInfo) XXX_Size() int {
	return xxx_messageInfo_URLLinkInfo.Size(m)
}
func (m *URLLinkInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_URLLinkInfo.DiscardUnknown(m)
}

var xxx_messageInfo_URLLinkInfo proto.InternalMessageInfo

func (m *URLLinkInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *URLLinkInfo) GetMaAppId() string {
	if m != nil {
		return m.MaAppId
	}
	return ""
}

func (m *URLLinkInfo) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *URLLinkInfo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *URLLinkInfo) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *URLLinkInfo) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

type QueryInfoRes struct {
	ErrNo                int64        `protobuf:"varint,1,opt,name=err_no,json=errNo" json:"err_no,omitempty"`
	ErrTips              string       `protobuf:"bytes,2,opt,name=err_tips,json=errTips" json:"err_tips,omitempty"`
	UrlLinkInfo          *URLLinkInfo `protobuf:"bytes,10,opt,name=url_link_info,json=urlLinkInfo" json:"url_link_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QueryInfoRes) Reset()         { *m = QueryInfoRes{} }
func (m *QueryInfoRes) String() string { return proto.CompactTextString(m) }
func (*QueryInfoRes) ProtoMessage()    {}
func (*QueryInfoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_share_ce06d67b2b437624, []int{4}
}
func (m *QueryInfoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryInfoRes.Unmarshal(m, b)
}
func (m *QueryInfoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryInfoRes.Marshal(b, m, deterministic)
}
func (dst *QueryInfoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInfoRes.Merge(dst, src)
}
func (m *QueryInfoRes) XXX_Size() int {
	return xxx_messageInfo_QueryInfoRes.Size(m)
}
func (m *QueryInfoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInfoRes.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInfoRes proto.InternalMessageInfo

func (m *QueryInfoRes) GetErrNo() int64 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *QueryInfoRes) GetErrTips() string {
	if m != nil {
		return m.ErrTips
	}
	return ""
}

func (m *QueryInfoRes) GetUrlLinkInfo() *URLLinkInfo {
	if m != nil {
		return m.UrlLinkInfo
	}
	return nil
}

type QueryQuotaReq struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	MaAppId              string   `protobuf:"bytes,2,opt,name=ma_app_id,json=maAppId" json:"ma_app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryQuotaReq) Reset()         { *m = QueryQuotaReq{} }
func (m *QueryQuotaReq) String() string { return proto.CompactTextString(m) }
func (*QueryQuotaReq) ProtoMessage()    {}
func (*QueryQuotaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_share_ce06d67b2b437624, []int{5}
}
func (m *QueryQuotaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryQuotaReq.Unmarshal(m, b)
}
func (m *QueryQuotaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryQuotaReq.Marshal(b, m, deterministic)
}
func (dst *QueryQuotaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryQuotaReq.Merge(dst, src)
}
func (m *QueryQuotaReq) XXX_Size() int {
	return xxx_messageInfo_QueryQuotaReq.Size(m)
}
func (m *QueryQuotaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryQuotaReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryQuotaReq proto.InternalMessageInfo

func (m *QueryQuotaReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *QueryQuotaReq) GetMaAppId() string {
	if m != nil {
		return m.MaAppId
	}
	return ""
}

type URLLInkQuota struct {
	UrlLinkUsed          int32    `protobuf:"varint,1,opt,name=url_link_used,json=urlLinkUsed" json:"url_link_used,omitempty"`
	UrlLinkLimit         int32    `protobuf:"varint,2,opt,name=url_link_limit,json=urlLinkLimit" json:"url_link_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URLLInkQuota) Reset()         { *m = URLLInkQuota{} }
func (m *URLLInkQuota) String() string { return proto.CompactTextString(m) }
func (*URLLInkQuota) ProtoMessage()    {}
func (*URLLInkQuota) Descriptor() ([]byte, []int) {
	return fileDescriptor_share_ce06d67b2b437624, []int{6}
}
func (m *URLLInkQuota) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URLLInkQuota.Unmarshal(m, b)
}
func (m *URLLInkQuota) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URLLInkQuota.Marshal(b, m, deterministic)
}
func (dst *URLLInkQuota) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URLLInkQuota.Merge(dst, src)
}
func (m *URLLInkQuota) XXX_Size() int {
	return xxx_messageInfo_URLLInkQuota.Size(m)
}
func (m *URLLInkQuota) XXX_DiscardUnknown() {
	xxx_messageInfo_URLLInkQuota.DiscardUnknown(m)
}

var xxx_messageInfo_URLLInkQuota proto.InternalMessageInfo

func (m *URLLInkQuota) GetUrlLinkUsed() int32 {
	if m != nil {
		return m.UrlLinkUsed
	}
	return 0
}

func (m *URLLInkQuota) GetUrlLinkLimit() int32 {
	if m != nil {
		return m.UrlLinkLimit
	}
	return 0
}

type QueryQuotaRes struct {
	ErrNo                int64         `protobuf:"varint,1,opt,name=err_no,json=errNo" json:"err_no,omitempty"`
	ErrTips              string        `protobuf:"bytes,2,opt,name=err_tips,json=errTips" json:"err_tips,omitempty"`
	UrlLinkQuota         *URLLInkQuota `protobuf:"bytes,10,opt,name=url_link_quota,json=urlLinkQuota" json:"url_link_quota,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QueryQuotaRes) Reset()         { *m = QueryQuotaRes{} }
func (m *QueryQuotaRes) String() string { return proto.CompactTextString(m) }
func (*QueryQuotaRes) ProtoMessage()    {}
func (*QueryQuotaRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_share_ce06d67b2b437624, []int{7}
}
func (m *QueryQuotaRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryQuotaRes.Unmarshal(m, b)
}
func (m *QueryQuotaRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryQuotaRes.Marshal(b, m, deterministic)
}
func (dst *QueryQuotaRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryQuotaRes.Merge(dst, src)
}
func (m *QueryQuotaRes) XXX_Size() int {
	return xxx_messageInfo_QueryQuotaRes.Size(m)
}
func (m *QueryQuotaRes) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryQuotaRes.DiscardUnknown(m)
}

var xxx_messageInfo_QueryQuotaRes proto.InternalMessageInfo

func (m *QueryQuotaRes) GetErrNo() int64 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *QueryQuotaRes) GetErrTips() string {
	if m != nil {
		return m.ErrTips
	}
	return ""
}

func (m *QueryQuotaRes) GetUrlLinkQuota() *URLLInkQuota {
	if m != nil {
		return m.UrlLinkQuota
	}
	return nil
}

func init() {
	proto.RegisterType((*GenerateReq)(nil), "developer.toutiao.com.GenerateReq")
	proto.RegisterType((*GenerateRes)(nil), "developer.toutiao.com.GenerateRes")
	proto.RegisterType((*QueryInfoReq)(nil), "developer.toutiao.com.QueryInfoReq")
	proto.RegisterType((*URLLinkInfo)(nil), "developer.toutiao.com.URLLinkInfo")
	proto.RegisterType((*QueryInfoRes)(nil), "developer.toutiao.com.QueryInfoRes")
	proto.RegisterType((*QueryQuotaReq)(nil), "developer.toutiao.com.QueryQuotaReq")
	proto.RegisterType((*URLLInkQuota)(nil), "developer.toutiao.com.URLLInkQuota")
	proto.RegisterType((*QueryQuotaRes)(nil), "developer.toutiao.com.QueryQuotaRes")
}

func init() { proto.RegisterFile("douyin-miniapp/share.proto", fileDescriptor_share_ce06d67b2b437624) }

var fileDescriptor_share_ce06d67b2b437624 = []byte{
	// 605 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0x56, 0xba, 0xdd, 0xd2, 0x3a, 0x5b, 0x0e, 0x16, 0x95, 0x42, 0xf8, 0x5b, 0xdc, 0x02, 0x4b,
	0xa5, 0x6e, 0xa4, 0x72, 0xeb, 0x0d, 0x0e, 0xa0, 0x95, 0xaa, 0x4a, 0x4d, 0x5b, 0x09, 0xf5, 0x12,
	0xb9, 0x9b, 0xe9, 0xae, 0xb5, 0x89, 0xed, 0xda, 0x4e, 0x45, 0xb9, 0x20, 0xc1, 0x85, 0x03, 0x17,
	0xc4, 0x8b, 0x20, 0x5e, 0x85, 0x57, 0xe0, 0x41, 0x90, 0x9d, 0xcd, 0x92, 0x48, 0x6d, 0x59, 0x95,
	0x0b, 0xb7, 0xf8, 0x9b, 0xc9, 0x37, 0xdf, 0x7c, 0x1e, 0x0f, 0x0a, 0x53, 0x51, 0x5c, 0x30, 0xbe,
	0x95, 0x33, 0xce, 0xa8, 0x94, 0x91, 0x1e, 0x53, 0x05, 0x7d, 0xa9, 0x84, 0x11, 0x78, 0x2d, 0x85,
	0x73, 0xc8, 0x84, 0x04, 0xd5, 0x37, 0xa2, 0x30, 0x8c, 0x8a, 0xfe, 0x50, 0xe4, 0xe1, 0xfd, 0x91,
	0x10, 0xa3, 0x0c, 0x22, 0x2a, 0x59, 0x44, 0x39, 0x17, 0x86, 0x1a, 0x26, 0xb8, 0x2e, 0x7f, 0x22,
	0x3f, 0x3c, 0xe4, 0xbf, 0x01, 0x0e, 0x8a, 0x1a, 0x88, 0xe1, 0x0c, 0x3f, 0x46, 0x1d, 0x3a, 0x1c,
	0x82, 0xd6, 0x89, 0x11, 0x13, 0xe0, 0x81, 0xd7, 0xf5, 0x7a, 0x2b, 0xb1, 0x5f, 0x62, 0x87, 0x16,
	0xc2, 0x21, 0x5a, 0xc9, 0x69, 0x42, 0xa5, 0x4c, 0x58, 0x1a, 0x2c, 0xb8, 0xf8, 0xad, 0x9c, 0xbe,
	0x94, 0x72, 0x90, 0xe2, 0xbb, 0x68, 0xd9, 0x06, 0x38, 0xcd, 0x21, 0x68, 0x95, 0x21, 0x2a, 0xe5,
	0x1e, 0xcd, 0x01, 0x63, 0xb4, 0x28, 0xa9, 0x19, 0x07, 0x8b, 0x0e, 0x76, 0xdf, 0xf8, 0x0e, 0x6a,
	0x9f, 0x15, 0xa0, 0x2e, 0x82, 0xb6, 0x03, 0xcb, 0x03, 0x7e, 0x84, 0x7c, 0x78, 0x27, 0x99, 0x82,
	0xc4, 0xb0, 0x1c, 0x82, 0xa5, 0xae, 0xd7, 0x6b, 0xc5, 0xa8, 0x84, 0x0e, 0x59, 0x0e, 0xe4, 0xb8,
	0xae, 0x59, 0xe3, 0x35, 0xb4, 0x04, 0x4a, 0x25, 0x5c, 0x38, 0xb5, 0xad, 0xb8, 0x0d, 0x4a, 0xed,
	0x09, 0xab, 0xc5, 0xc2, 0x86, 0x49, 0x5d, 0xc9, 0x04, 0xa5, 0x0e, 0x99, 0xd4, 0x36, 0x54, 0xa8,
	0x2c, 0xc9, 0x18, 0x9f, 0x54, 0x32, 0x0b, 0x95, 0xed, 0x32, 0x3e, 0x21, 0x63, 0xd4, 0xd9, 0xb7,
	0x2a, 0x06, 0xfc, 0x54, 0xcc, 0x69, 0x48, 0x9d, 0x6d, 0xa1, 0xc1, 0xd6, 0xf4, 0xaa, 0xd5, 0xf0,
	0x8a, 0x7c, 0xf7, 0x90, 0x7f, 0x14, 0xef, 0xda, 0x3c, 0x5b, 0xcc, 0xb6, 0x3d, 0x54, 0x40, 0xcd,
	0xb4, 0xed, 0xb2, 0x17, 0x54, 0x42, 0xb6, 0xed, 0xff, 0xc0, 0xf8, 0xcf, 0x5e, 0xc3, 0x9d, 0x9b,
	0x58, 0xff, 0x1a, 0xad, 0x56, 0x66, 0x25, 0x8c, 0x9f, 0x8a, 0x00, 0x75, 0xbd, 0x9e, 0xbf, 0x4d,
	0xfa, 0x97, 0x4e, 0x6f, 0xbf, 0x66, 0x50, 0xec, 0x4f, 0x5d, 0xb5, 0x07, 0xb2, 0x87, 0x56, 0x9d,
	0x92, 0xfd, 0x42, 0x18, 0xfa, 0xef, 0x93, 0x4b, 0xde, 0xa2, 0x8e, 0xad, 0x35, 0xe0, 0x13, 0xc7,
	0x88, 0x49, 0x4d, 0x67, 0xa1, 0x21, 0x75, 0x7c, 0xed, 0x99, 0x86, 0x23, 0x0d, 0x29, 0xde, 0x40,
	0xb7, 0x67, 0x39, 0x19, 0xcb, 0x99, 0x71, 0xa4, 0xed, 0xb8, 0x33, 0x4d, 0xda, 0xb5, 0x18, 0xf9,
	0xe2, 0x35, 0xa5, 0xde, 0xc4, 0xb5, 0x41, 0xad, 0xd2, 0x99, 0xa5, 0x99, 0xda, 0xb6, 0x7e, 0x8d,
	0x6d, 0x55, 0x2b, 0x33, 0x39, 0xee, 0xb4, 0xfd, 0xb5, 0x85, 0x3a, 0x07, 0x76, 0x6d, 0x1c, 0x80,
	0x3a, 0x67, 0x43, 0xc0, 0xef, 0xd1, 0x72, 0xf5, 0x9a, 0xf0, 0x55, 0xd7, 0x50, 0x5b, 0x11, 0xe1,
	0xdf, 0x73, 0x34, 0x79, 0xfa, 0xf1, 0xe7, 0xaf, 0x6f, 0x0b, 0x5d, 0x72, 0xaf, 0x5c, 0x3b, 0x52,
	0xea, 0xa8, 0xd2, 0x1f, 0x8d, 0xa6, 0x79, 0x3b, 0xde, 0x26, 0xfe, 0x80, 0x56, 0x66, 0xf3, 0x84,
	0xaf, 0x6a, 0xa6, 0xfe, 0x1e, 0xc3, 0x39, 0x92, 0x34, 0xe9, 0xb9, 0xf2, 0x84, 0x3c, 0xb8, 0xa4,
	0xbc, 0x1b, 0x75, 0x37, 0x7a, 0x56, 0xc0, 0x27, 0x0f, 0xa1, 0x3f, 0x97, 0x83, 0x37, 0xae, 0x63,
	0xaf, 0x46, 0x2d, 0x9c, 0x27, 0x4b, 0x93, 0xe7, 0x4e, 0xc4, 0x3a, 0x79, 0x78, 0xa5, 0x08, 0x77,
	0x93, 0x3b, 0xde, 0xe6, 0xab, 0x67, 0xc7, 0x4f, 0x46, 0xcc, 0x8c, 0x8b, 0x13, 0x4b, 0x13, 0xa5,
	0x70, 0xbe, 0x25, 0x24, 0x70, 0xfb, 0x5b, 0x73, 0xdf, 0x9f, 0x2c, 0xb9, 0xad, 0xfd, 0xe2, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0x92, 0xfd, 0xdc, 0x08, 0x06, 0x00, 0x00,
}
