// Code generated by protoc-gen-go_api(github.com/dev-openapi/protoc-gen-go_api version=v1.0.3). DO NOT EDIT.
// source: douyin-miniapp/share.proto

package douyin_miniapp

import (
	context "context"
	fmt "fmt"
	io "io"
	json "encoding/json"
	bytes "bytes"
	http "net/http"
	strings "strings"
	url "net/url"
	multipart "mime/multipart"
)
// Reference imports to suppress errors if they are not otherwise used.
var _ = context.Background
var _ = http.NewRequest
var _ = io.Copy
var _ = bytes.Compare
var _ = json.Marshal
var _ = strings.Compare
var _ = fmt.Errorf
var _ = url.Parse
var _ = multipart.ErrMessageTooLarge


// Client API for Share service

type ShareService interface {
	// Generate  生成分享 https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/server/share/url-link-generate
	Generate(ctx context.Context, in *GenerateReq, opts ...Option) (*GenerateRes, error)
	// QueryInfo  查询生成的分享信息 https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/server/share/url-link-query
	QueryInfo(ctx context.Context, in *QueryInfoReq, opts ...Option) (*QueryInfoRes, error)
	// QueryQuota  查询配额 https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/server/share/url-link-query-quota
	QueryQuota(ctx context.Context, in *QueryQuotaReq, opts ...Option) (*QueryQuotaRes, error)
}

type shareService struct {
	// opts
	opts *Options
}

func NewShareService(opts ...Option) ShareService {
	opt := newOptions(opts...)
	if len(opt.addr) <= 0 {
		opt.addr = "https://developer.toutiao.com"
	}
	return &shareService {
		opts: opt,
	}
}


func (c *shareService) Generate(ctx context.Context, in *GenerateReq, opts ...Option) (*GenerateRes, error) {
	var res GenerateRes
	// options
	opt := buildOptions(c.opts, opts...)
	headers := make(map[string]string)
	// route
	rawURL := fmt.Sprintf("%s/api/apps/url_link/generate", opt.addr)

	// body
	bs, err := json.Marshal(in)
	if err != nil {
		return nil, err
	}
	body := bytes.NewReader(bs)
	headers["Content-Type"] = "application/json"

	req, err := http.NewRequest("POST", rawURL, body)
	if err != nil {
		return nil, err
	}
	
	// header
	for k, v := range headers {
		req.Header.Set(k, v)
	}
	resp, err := opt.DoRequest(ctx, opt.client, req)
	if err != nil {
		return nil, err
	}
	err = opt.DoResponse(ctx, resp, &res)
	return &res, err 

}

func (c *shareService) QueryInfo(ctx context.Context, in *QueryInfoReq, opts ...Option) (*QueryInfoRes, error) {
	var res QueryInfoRes
	// options
	opt := buildOptions(c.opts, opts...)
	headers := make(map[string]string)
	// route
	rawURL := fmt.Sprintf("%s/api/apps/url_link/query_info", opt.addr)

	// body
	bs, err := json.Marshal(in)
	if err != nil {
		return nil, err
	}
	body := bytes.NewReader(bs)
	headers["Content-Type"] = "application/json"

	req, err := http.NewRequest("POST", rawURL, body)
	if err != nil {
		return nil, err
	}
	
	// header
	for k, v := range headers {
		req.Header.Set(k, v)
	}
	resp, err := opt.DoRequest(ctx, opt.client, req)
	if err != nil {
		return nil, err
	}
	err = opt.DoResponse(ctx, resp, &res)
	return &res, err 

}

func (c *shareService) QueryQuota(ctx context.Context, in *QueryQuotaReq, opts ...Option) (*QueryQuotaRes, error) {
	var res QueryQuotaRes
	// options
	opt := buildOptions(c.opts, opts...)
	headers := make(map[string]string)
	// route
	rawURL := fmt.Sprintf("%s/api/apps/url_link/query_quota", opt.addr)

	// body
	bs, err := json.Marshal(in)
	if err != nil {
		return nil, err
	}
	body := bytes.NewReader(bs)
	headers["Content-Type"] = "application/json"

	req, err := http.NewRequest("POST", rawURL, body)
	if err != nil {
		return nil, err
	}
	
	// header
	for k, v := range headers {
		req.Header.Set(k, v)
	}
	resp, err := opt.DoRequest(ctx, opt.client, req)
	if err != nil {
		return nil, err
	}
	err = opt.DoResponse(ctx, resp, &res)
	return &res, err 

}
